Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-12, with the labels that each got.

#2139 feat: added graphql reverse JSON and comapre JSON functions
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  package.json
  yarn.lock
Labels: feature

#2141 Feat/query builder implementation with breadcrum
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/icons/ThreeDot.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-status/ResponseStatus.svelte
Labels: story

#2142 feat: added refetch schema and refresh schema and editor sync up functions [#2088]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
Labels: front end

#2124 feat: Added custom header [#2114]
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-desktop/src/components/App.svelte
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  packages/@sparrow-common/src/components/default-header/DefaultHeader.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-library/src/icons/CrossIconV2.svelte
  packages/@sparrow-library/src/icons/DoubleResize.svelte
  packages/@sparrow-library/src/icons/Expand.svelte
  packages/@sparrow-library/src/icons/MiniMize.svelte
  packages/@sparrow-library/src/icons/Square.svelte
  packages/@sparrow-library/src/icons/index.ts
Labels: story

#2144 fix: add graphql mutation [#2081]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  packages/@sparrow-common/src/types/workspace/graphql-request-tab.ts
  packages/@sparrow-common/src/utils/init-graphql-tab.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
Labels: story

#2145 feat: added Variables flow in Graphql
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src/adapter/graphql-tab.ts
  apps/@sparrow-desktop/src/components/App.svelte
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-dto.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-tab.ts
  packages/@sparrow-common/src/utils/init-graphql-tab.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-variables/RequestVariables.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/utils/decode-graphql.ts
Labels: bug, feature

#2147 fix : header bugs in mac
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte
Labels: bug

#2135 Feat : Completed Cloud Agent and proxy agent API Request Workflow
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-library/src/icons/CheckCircle.svelte
  packages/@sparrow-library/src/icons/index.ts
Labels: task

#2177 Fix/clear query mutation operation
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
Labels: story

#2169 fix: UI related bugs in webapp
  packages/@sparrow-library/src/ui/carousel/Carousel.svelte
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: bug

#2152 fix: fixed the tab button by disabling it when the modal is open
  packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
Labels: bug

#2175 fix : shortcuts visibility in rest api console
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
Labels: bug

#2178 fix: unnecessary re-renders of code mirror
  packages/@sparrow-library/src/forms/editor/Editor.svelte
Labels: bug

#2198 feat: added reverse query to schema feature []
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
Labels: feature

#2197 fix: graphql save in folder bug [#2083]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-base.ts
Labels: bug

#2224 bug:resolved-overlapping[#2168]
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug

#2201 fix: fixed the empty name issue in saving collection and folder from …
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug

#2193 Fix: fixed custom header visibility
  packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte
Labels: bug

#2154 fix: fixed feedback filter issue [#2136]
  apps/@sparrow-desktop/src/services/canny.service.ts
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
Labels: bug

#2241 Feat: implement socket io browser agent
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/package.json
  apps/@sparrow-web/src/adapter/graphql-tab.ts
  apps/@sparrow-web/src/adapter/index.ts
  apps/@sparrow-web/src/adapter/socket-io-tab.ts
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/types/workspace/workspace-base.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/utils/decode-socketio.ts
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
  yarn.lock
Labels: story

#2248 feat: added sparrow edge functionality from auth [#2159]
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
Labels: story

#2233 Feat: Revamped init page in Desktop app
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  apps/@sparrow-desktop/src/styles/style.scss
  packages/@sparrow-common/src/components/background/Background.svelte
  packages/@sparrow-common/src/images/SparrowBackgroundV2.svg
  packages/@sparrow-common/src/images/index.ts
  packages/@sparrow-library/src/icons/AiSparkleV2.svelte
  packages/@sparrow-library/src/icons/AiSparkleV3.svelte
  packages/@sparrow-library/src/icons/index.ts
Labels: story

#2255 FIx: Fixed Color issue in init page button
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
Labels: bug

#2275 feat: login desktop with token feature [#2192]
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
Labels: story

#2309 fix: save socket io and ws from top tab []
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug

#2318 Add Coding Patterns and Guidelines Documentation
  docs/CODE_PATTERNS.md
Labels: documentation

#2320 fix: resolved multiple toast message appearing/[#2234]
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: bug, regression

#2265 Fix: resolved collection placeholder message[#2217]
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
Labels: bug

#2239 fix: resolved-workspace-sorting[#1923]
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: bug

#2232 Fix: Added Launch Desktop button in Workspace[#2173]
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/lanuch-desktop/LanuchDesktop.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug, design

#2333 fix: failed navigation to web for mac [#2266]
  apps/@sparrow-desktop/src/components/App.svelte
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/LoginPage.svelte
  apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/login-page.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/redirect/Redirect.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body/ResponseBody.svelte
Labels: bug

#2344 feat: sparrow web app setup []
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
Labels: front end, feature

#2346 feat: Introduced the API Test Flow Management feature, enabling streamlined testing workflows for APIs.
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/repositories/testflow.repository.ts
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: story

#2356 feat: integrate user agent to web app testflow [#2298]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#2353 Feat: Webapp Sparrow Edge - Teams & Workspaces
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/sub-component/PopupHint.svelte
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
Labels: story

#2349 fix: updated webapp agent dropdown size[#2338]
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: bug

#2366 fix: validation message in invite workspace popup
  packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte
Labels: bug

#2347 fix : Teams edit ,delete icons size issue[#2342]
  packages/@sparrow-common/src/features/create-team/components/icon-uploader/IconUploader.svelte
Labels: bug

#2378 fix: resolved github star navigation in workspace.
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#2380 feat: added support for Swagger and localhost support in collection import [#2306]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
Labels: story, front end
