Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-07, with the labels that each got.

#1154 Feat: Added Teams Details LHS UI part
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.svelte
  src/packages/@app/styles/style.scss
  src/packages/@teams/common/components/api-list-items/ApiListItem.svelte
  src/packages/@teams/common/components/index.ts
  src/packages/@teams/common/stores/index.ts
  src/packages/@teams/common/stores/splitpane.ts
  src/packages/@teams/features/recent-apis/index.ts
  src/packages/@teams/features/recent-apis/layout/RecentApi.svelte
  src/packages/@teams/features/recent-apis/layout/index.ts
  src/packages/@teams/features/recent-workspace/index.ts
  src/packages/@teams/features/recent-workspace/layout/RecentWorkspace.svelte
  src/packages/@teams/features/recent-workspace/layout/index.ts
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
Labels: story, front end, UI

#1152 Feat: iimplement create team feature, where user can create their custom teams [1084]
  src/packages/@app/adapter/index.ts
  src/packages/@app/adapter/team.ts
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.svelte
  src/packages/@app/repositories/team.repository.ts
  src/packages/@app/styles/style.scss
  src/packages/@library/forms/Input/Input.svelte
  src/packages/@library/forms/textarea/Textarea.svelte
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
  src/packages/@teams/features/create-team/components/file-type/FileType.svelte
  src/packages/@teams/features/create-team/components/icon-uploader/IconUploader.svelte
  src/packages/@teams/features/create-team/components/index.ts
  src/packages/@teams/features/create-team/components/team-actions/TeamActions.svelte
  src/packages/@teams/features/create-team/components/team-description/TeamDescription.svelte
  src/packages/@teams/features/create-team/components/team-icon/TeamIcon.svelte
  src/packages/@teams/features/create-team/components/team-name/TeamName.svelte
  src/packages/@teams/features/create-team/constants/description.ts
  src/packages/@teams/features/create-team/constants/icon.ts
  src/packages/@teams/features/create-team/constants/index.ts
  src/packages/@teams/features/create-team/constants/name.ts
  src/packages/@teams/features/create-team/index.ts
  src/packages/@teams/features/create-team/layout/CreateTeam.svelte
  src/packages/@teams/features/create-team/types/form.ts
  src/packages/@teams/features/create-team/types/index.ts
  src/packages/@teams/features/index.ts
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
Labels: feature

#1159 feat: create workspace from dropdown
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@common/components/header/Header.svelte
  src/packages/@library/forms/select/Select.svelte
  src/packages/@library/forms/select/menu-items/MenuItemsV3.svelte
  src/packages/@teams/features/create-workspace/components/index.ts
  src/packages/@teams/features/create-workspace/components/workspace-actions/WorkspaceActions.svelte
  src/packages/@teams/features/create-workspace/components/workspace-name/WorkspaceName.svelte
  src/packages/@teams/features/create-workspace/components/workspace-team/WorkspaceTeam.svelte
  src/packages/@teams/features/create-workspace/constants/index.ts
  src/packages/@teams/features/create-workspace/constants/name.ts
  src/packages/@teams/features/create-workspace/constants/team.ts
  src/packages/@teams/features/create-workspace/index.ts
  src/packages/@teams/features/create-workspace/layout/CreateWorkspace.svelte
  src/packages/@teams/features/create-workspace/types/form.ts
  src/packages/@teams/features/create-workspace/types/index.ts
Labels: story, front end, feature

#1158 feat: Added search workspace functionality [1097]
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
Labels: story

#1163 feat: Added Team details LHS part with navigation [1074]
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.svelte
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
Labels: story

#1165 feat: added workspace dropdown [1117]
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@common/components/header/Header.svelte
  src/packages/@library/forms/select/Select.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
Labels: story, front end, feature

#1155 fix: Bulk Edit Bugs [123]
  src/packages/@library/forms/textarea/Textarea.svelte
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
Labels: bug

#1168 fix: invite flow styling [#1106]
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@teams/features/team-members/components/member/Member.svelte
Labels: design

#1182 Fix/bugs from sprint two
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@teams/features/create-team/constants/icon.ts
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceSetting.svelte
Labels: bug

#1183 Fix/fixed UI bugs sprint 2
  src/packages/@app/styles/style.scss
  src/packages/@common/components/header/Header.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
Labels: bug

#1196 feat: implement teams settings [#1147]
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
  src/packages/@app/styles/style.scss
  src/packages/@library/icons/Lock.svelte
  src/packages/@library/icons/index.ts
  src/packages/@teams/features/create-team/types/form.ts
  src/packages/@teams/features/index.ts
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@teams/features/team-settings/components/index.ts
  src/packages/@teams/features/team-settings/components/settings-navigator/SettingsNavigator.svelte
  src/packages/@teams/features/team-settings/components/team-profile/TeamsProfile.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/index.ts
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/team-owner/TeamOwner.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
  src/packages/@teams/features/team-settings/constants/index.ts
  src/packages/@teams/features/team-settings/constants/team-profile.ts
  src/packages/@teams/features/team-settings/index.ts
  src/packages/@teams/features/team-settings/layout/TeamSettings.svelte
  src/packages/@teams/features/team-settings/types/index.ts
  src/packages/@teams/features/team-settings/types/settings-navigator.ts
  src/packages/@teams/features/team-settings/types/team-profile.ts
Labels: story

#1194 Fix: fixed UI bugs sprint 2
  src/packages/@app/styles/style.scss
  src/packages/@teams/features/recent-apis/layout/RecentApi.svelte
  src/packages/@teams/features/recent-workspace/layout/RecentWorkspace.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
  src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug, UI

#1204 Feat: Add workspace level invite flow, enhance UI, and refactor workspace explorer [#1086]
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@app/repositories/workspace.repository.ts
  src/packages/@app/styles/style.scss
  src/packages/@library/forms/index.ts
  src/packages/@library/forms/multi-select/MultiSelect.svelte
  src/packages/@library/forms/multi-select/types/index.ts
  src/packages/@library/forms/multi-select/types/multi-select.ts
  src/packages/@library/icons/index.ts
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@teams/features/team-members/components/member/Member.svelte
  src/packages/@teams/features/team-members/components/profile/Profile.svelte
  src/packages/@teams/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
  src/packages/@workspaces/features/index.ts
  src/packages/@workspaces/features/invite-to-workspace/components/index.ts
  src/packages/@workspaces/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
  src/packages/@workspaces/features/invite-to-workspace/index.ts
  src/packages/@workspaces/features/invite-to-workspace/layout/InviteToWorkspace.svelte
  src/packages/@workspaces/features/invite-to-workspace/types/index.ts
  src/packages/@workspaces/features/invite-to-workspace/types/invite-picker.ts
  src/packages/@workspaces/features/workspace-explorer/components/collection-count/CollectionCount.svelte
  src/packages/@workspaces/features/workspace-explorer/components/index.ts
  src/packages/@workspaces/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/index.ts
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
  src/packages/@workspaces/features/workspace-explorer/index.ts
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceSetting.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/index.ts
Labels: story

#1242 Fix: Teams icon Update Issue on Role Change in Teams Module
  src/packages/@common/features/delete-workspace/layout/DeleteWorkspace.svelte
  src/packages/@library/ui/icon-fallback/IconFallback.svelte
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@teams/features/team-members/components/member/Member.svelte
Labels: bug

#1249 feat: implement teams levels permissions
  src/packages/@teams/common/compopnents/rows/Rows.svelte
  src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
Labels: story

#1214 Feat: Added Viewing Team Member Popup
  src/packages/@app/services/team.service.ts
  src/packages/@app/styles/style.scss
  src/packages/@deprecate/assets/icons/DownArrow.svelte
  src/packages/@library/forms/select/Select.svelte
  src/packages/@library/icons/Arrow.svelte
  src/packages/@library/ui/modal/Modal.svelte
  src/packages/@teams/features/team-members/components/profile/Profile.svelte
  src/packages/@teams/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
Labels: story

#1253 Fix: update create new team about message
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@library/forms/multi-select/MultiSelect.svelte
  src/packages/@library/icons/DownArrow.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/label/Label.svelte
  src/packages/@teams/features/create-team/components/team-description/TeamDescription.svelte
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: bug

#1257 feat: added workspace updates functionality [#1169]
  src/packages/@app/database/database.ts
  src/packages/@app/models/updates.model.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@app/repositories/updates.repository.ts
  src/packages/@app/services/updates.service.ts
  src/packages/@workspaces/features/workspace-explorer/components/collection-count/CollectionCount.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: story, design, front end

#1254 Feat: Added leaving team functionality
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
  src/packages/@library/icons/MoreOptions.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/index.ts
  src/packages/@teams/features/index.ts
  src/packages/@teams/features/leave-team/index.ts
  src/packages/@teams/features/leave-team/layout/LeaveTeam.svelte
  src/packages/@teams/features/leave-team/layout/index.ts
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte
Labels: story

#1258 feat: Added Managing Workspace member dropdown with functionality
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: story

#1268 feat: workspace level permissions
  src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.svelte
  src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.svelte
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@environments/common/components/tabular-input/TabularInput.svelte
  src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
  src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte
  src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte
  src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
  src/packages/@workspaces/features/collection-list/components/request/Request.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
  src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: front end

#1271 feat: added local support for teams and workspaces
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.svelte
  src/packages/@common/components/sidebar/Sidebar.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
Labels: front end

#1267 Feat: Added bulk edit color coding
  src/packages/@app/styles/style.scss
  src/packages/@library/forms/editor/Editor.svelte
  src/packages/@library/ui/dropdown/Dropdown.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
  src/packages/@workspaces/common/components/tabular-input/sub-component/BulkEditEditor.svelte
  src/packages/@workspaces/common/components/tabular-input/sub-component/bulk-edit-theme.ts
  src/packages/@workspaces/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-parameters/RequestParameters.svelte
Labels: story

#1284 fix: bug fixes
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@common/features/delete-workspace/layout/DeleteWorkspace.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
Labels: bug

#1285 fix: Added the Info Pop up for 10 sec in local support header [#1273]
  src/packages/@common/components/header/Header.svelte
  src/packages/@common/components/header/sub-component/PopupHint.svelte
  src/packages/@library/icons/CrossIconRounded.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/tooltip/Tooltip.svelte
Labels: bug

#1308 fix: question mark not being removed from base url on query param toggle
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
Labels: bug

#1320 fix: remove unwanted library and fixed create workspace bug []
  package.json
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  yarn.lock
Labels: bug

#1310 Fix/bug fixes sprint 3
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@common/components/header/Header.svelte
  src/packages/@teams/common/compopnents/rows/Rows.svelte
  src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte
  src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
  src/packages/@teams/features/team-settings/constants/team-profile.ts
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
Labels: bug

#1332 feat: implementation of an AI Assistant feature within the request API.
  package.json
  src/packages/@app/database/database.ts
  src/packages/@app/models/tab.model.ts
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
  src/packages/@app/services/ai-assistant.service.ts
  src/packages/@app/styles/style.scss
  src/packages/@common/icons/SparrowAI.svelte
  src/packages/@common/icons/index.ts
  src/packages/@common/images/generating.gif
  src/packages/@common/images/index.ts
  src/packages/@common/types/workspace/index.ts
  src/packages/@common/types/workspace/request.ts
  src/packages/@common/utils/init-request-tab.ts
  src/packages/@deprecate/utils/dto/ai-assistant.ts
  src/packages/@deprecate/utils/enums/mixpanel-events.enum.ts
  src/packages/@environments/common/components/tabular-input/TabularInput.svelte
  src/packages/@library/icons/AiSparkle.svelte
  src/packages/@library/icons/AngleLeft.svelte
  src/packages/@library/icons/Copy2.svelte
  src/packages/@library/icons/Dislike.svelte
  src/packages/@library/icons/Generate.svelte
  src/packages/@library/icons/Like.svelte
  src/packages/@library/icons/Refresh.svelte
  src/packages/@library/icons/Send.svelte
  src/packages/@library/icons/index.ts
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@teams/features/team-settings/components/settings-navigator/SettingsNavigator.svelte
  src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte
  src/packages/@workspaces/features/chat-bot/assests/Copy.svg
  src/packages/@workspaces/features/chat-bot/assests/index.ts
  src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  src/packages/@workspaces/features/chat-bot/components/ai-chat-toggler/AiChatToggler.svelte
  src/packages/@workspaces/features/chat-bot/components/ai-suggestion-box/AISuggestionBox.svelte
  src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
  src/packages/@workspaces/features/chat-bot/components/index.ts
  src/packages/@workspaces/features/chat-bot/components/prompt-input/PromptInput.svelte
  src/packages/@workspaces/features/chat-bot/index.ts
  src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte
  src/packages/@workspaces/features/chat-bot/layout/index.ts
  src/packages/@workspaces/features/chat-bot/types/index.ts
  src/packages/@workspaces/features/chat-bot/types/scroll.ts
  src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
  src/packages/@workspaces/features/index.ts
  src/packages/@workspaces/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  yarn.lock
Labels: story
