Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-08, with the labels that each got.

#1357 Fix/1228/revert unsaved api red dot on backtrack
  src/packages/@app/database/database.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@common/utils/compare-array.ts
  src/packages/@common/utils/index.ts
Labels: bug

#1349 fix: unselect selected environment on deletion [#1317]
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
Labels: bug

#1358 fix: changed instructions and fixed bugs []
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@deprecate/utils/dto/ai-assistant.ts
  src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/common/components/codemirror-input/CodeMirrorInput.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: bug

#1360 feat: implement delays to ai response generation for chunk data
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
  src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte
Labels: bug

#1353 fix: Fixed missing Add Member option in workspace list view [#1278]
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
  src/packages/@teams/common/compopnents/rows/Rows.svelte
  src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte
Labels: bug

#1350 Fix/bug fixes from sprint
  src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@workspaces/common/components/missed-environment/MissedEnvironment.svelte
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte
  src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte
Labels: bug

#1368 fix: chatbot instructions [#1361]
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte
Labels: bug

#1384 Fix/adding animations in bot
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte
Labels: bug

#1393 feat: added websocket RPC flow []
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src/packages/@deprecate/api/api.common.ts
Labels: story, front end, feature

#1389 fix: This code handles cURL popup on Client-Side[1288]
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@workspaces/features/import-curl/layout/ImportCurl.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
Labels: bug

#1406 Feat: implement environment at web socket
  src/packages/@app/pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  src/packages/@deprecate/api/api.common.ts
  src/packages/@workspaces/features/rest-explorer/utils/decode-websocket.ts
  src/packages/@workspaces/features/rest-explorer/utils/index.ts
  src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: story

#1416 fix: websocket bugs [#1336]
  src/packages/@app/styles/style.scss
  src/packages/@common/components/header/Header.svelte
Labels: bug

#1425 feat: added websocket in AI #1347
  package.json
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
  src/packages/@app/services/ai-assistant.ws.service.ts
  src/packages/@app/store/ws.store.ts
  src/packages/@deprecate/utils/dto/ai-assistant.ts
  yarn.lock
Labels: front end

#1435 fix: update husky pre hook check messages
  .husky/commit-msg
  .husky/pre-commit
Labels: enhancement
