Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-10, with the labels that each got.

#1693 fix: deprecate assets and package scripts
  apps/@sparrow-desktop/src/pages/Auth/entry-point/EntryPoint.svelte
  apps/@sparrow-desktop/src/pages/Auth/login-page/LoginPage.svelte
  package.json
  packages/@sparrow-deprecate/src/assets/index.ts
Labels: story

#1698 Feat/implement web app login flow
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-web/src/components/App.svelte
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/utils/jwt.ts
Labels: story

#1666 fix: Fixed renaming issue in environment, collection and test flow [#1651]
  src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
  src/packages/@workspaces/features/collection-list/components/request/Request.svelte
  src/packages/@workspaces/features/collection-list/components/web-socket/WebSocket.svelte
  src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
Labels: bug

#1730 fix: handle null signal rejection for http client
  src/packages/@deprecate/api/api.common.ts
Labels: bug

#1726 feat: added postman collection support [#1662]
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/services/collection.service.ts
  src/packages/@app/styles/style.scss
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
Labels: story, front end, feature

#1622 FIX: [Rest API Tool] Time delay when navigating to lengthy Header/Parameters
  package.json
  src/packages/@library/ui/skeleton/Skeleton.svelte
  src/packages/@library/ui/skeleton/index.ts
  src/packages/@workspaces/common/components/codemirror-input/CodeMirrorInput.svelte
  src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  src/packages/@workspaces/common/components/tabular-input/LazyElement.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
  yarn.lock
Labels: bug, front end

#1729 fix: fixed websocket multiple response issue
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@deprecate/api/api.common.ts
  src/packages/@workspaces/features/socket-explorer/store/websocket.ts
Labels: bug

#1734 feat: add response listener to rest api using store and hashmap
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body/ResponseBody.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-navigator/ResponseNavigator.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/rest-explorer/store/rest-explorer.ts
Labels: bug

#1735 fix: default response state in rest api tool
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
Labels: bug

#1737 fix: perform rxdocument delete operation for env, testflow and colletions
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/Testflow.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
  src/packages/@app/repositories/collection.repository.ts
  src/packages/@app/repositories/environment.repository.ts
  src/packages/@app/repositories/testflow.repository.ts
  src/packages/@deprecate/api/api.common.ts
Labels: bug

#1722 fix: fixed bugs from loop doc [#1686]
  src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
  src/packages/@app/pages/Auth/redirect/Redirect.svelte
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  src/packages/@app/services/canny.service.ts
  src/packages/@app/styles/style.scss
  src/packages/@common/components/sidebar/Sidebar.svelte
  src/packages/@common/features/delete-workspace/layout/DeleteWorkspace.svelte
  src/packages/@common/types/canny/canny.ts
  src/packages/@deprecate/store/auth.store.ts
  src/packages/@library/icons/BoxBarIcon.svelte
  src/packages/@library/icons/MessageDisabledIcon.svelte
  src/packages/@library/icons/MessageIcon.svelte
  src/packages/@library/icons/PostIcon.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/index.ts
  src/packages/@support/common/components/Attachment/Attachment.svelte
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/common/components/HelpInfo-Card/HelpInfoCard.svelte
  src/packages/@support/common/components/Upvote.svelte
  src/packages/@support/common/components/index.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
  src/packages/@support/features/community/layout/Community.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
  src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
  src/packages/@teams/features/team-settings/components/settings-navigator/SettingsNavigator.svelte
  src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/workspace-default/components/card/Card.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: bug

#1739 Fix:Fixed workspace page UI issue [#1614]
  src/packages/@library/forms/multi-select/MultiSelect.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#1742 fix: fixed workspace list view pagination ui [#1614]
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: bug

#1747 fix: perform teams rxdocument deletion
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.svelte
  src/packages/@app/repositories/team.repository.ts
  src/packages/@deprecate/api/api.common.ts
  src/packages/@deprecate/utils/enums/enums.ts
Labels: bug

#1749 Fix/admin permissions for the user itself
  src/packages/@teams/features/team-members/components/profile/Profile.svelte
  src/packages/@teams/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
Labels: bug

#1750 Update message on search query for left panel
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte
Labels: bug, design

#1745 fix: fixed some ui issues mentioned in the loop doc [#1686]
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/services/canny.service.ts
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: bug

#1751 fix: trim workspace name for creation
  src/packages/@teams/features/create-workspace/components/workspace-actions/WorkspaceActions.svelte
  src/packages/@teams/features/create-workspace/components/workspace-name/WorkspaceName.svelte
Labels: bug

#1755 fix: remove uninstaller script for windows
  src-tauri/tauri.conf.json
Labels: bug

#1754 fix: Fixed loop doc ui bugs [#1234]
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/services/canny.service.ts
  src/packages/@deprecate/components/collections/collection-tab/MyCollection.svelte
  src/packages/@deprecate/components/collections/collections-list/CollectionList.old.svelte
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
  src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  src/packages/@teams/features/team-members/layout/TeamMembers.svelte
  src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/socket-explorer/components/response-data/ResponseData.svelte
  src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: bug

#1756 Fix: Fixed left panel text UI and naming convention.
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
  src/packages/@workspaces/features/collection-list/components/request/Request.svelte
  src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
  src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
Labels: bug

#1757 fix: empty search text
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#1758 Fix: Fixed notifications UI text
  src/packages/@app/components/App.svelte
  src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
  src/packages/@app/pages/Auth/forgot-password/forgot-password.ts
  src/packages/@app/pages/Auth/login-page/login-page.ts
  src/packages/@app/pages/Auth/register-page/register-page.ts
  src/packages/@app/pages/Auth/reset-password/reset-password.ts
  src/packages/@app/pages/Auth/update-password/update-password.ts
  src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/Collections.ViewModel.old.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Collections/Testflow.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
  src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/Home/Waiting.svelte
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.ViewModel.ts
  src/packages/@app/pages/Teams/Teams.old.svelte
  src/packages/@app/pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  src/packages/@common/features/app-updater/layout/AppUpdater.svelte
  src/packages/@deprecate/api/api.common.ts
  src/packages/@deprecate/components/Modal/AutoUpdateDialog.svelte
  src/packages/@deprecate/components/Modal/CollectionPopup.svelte
  src/packages/@deprecate/components/Modal/FilePopup.svelte
  src/packages/@deprecate/components/Modal/FolderPopup.svelte
  src/packages/@deprecate/components/collections/collection-tab/MyCollection.svelte
  src/packages/@deprecate/components/collections/collections-list/CollectionList.old.svelte
  src/packages/@deprecate/components/collections/collections-list/collection/Collection.old.svelte
  src/packages/@deprecate/components/collections/collections-list/folder/Folder.old.svelte
  src/packages/@deprecate/components/collections/collections-list/import-curl/ImportCurl.old.svelte
  src/packages/@deprecate/components/collections/req-res-section/SidebarRight.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/add-environment-popup/AddEnvironment.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/close-popup/ClosePopup.old.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/response-body-section/ResponseBody.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/save-request/SaveRequest.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/sub-components-header/DefaultTabBar.svelte
  src/packages/@deprecate/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte
  src/packages/@deprecate/components/environments/environments-list/EnvironmentList.svelte
  src/packages/@deprecate/components/environments/environments-list/sub-components/environment-tab/EnvironmentTab.svelte
  src/packages/@deprecate/components/header/header-dashboard/HeaderDashboardDropdown.svelte
  src/packages/@deprecate/components/workspace/team-invite/TeamInvite.svelte
  src/packages/@deprecate/components/workspace/workspace-tab/myWorkspace.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
  src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  src/packages/@workspaces/features/rest-explorer/components/rest-extension-panel/RestExtensionPanel.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
  src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
Labels: enhancement, improvement

#1760 fix: Fixed add feedback issue [#1724]
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
Labels: bug

#1761 fix: undefined on collection deletion
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
  src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
Labels: bug

#1773 Fix/handle tab deletion with sync to teams and collaboration
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Collections/Testflow.ViewModel.ts
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/repositories/collection.repository.ts
  src/packages/@app/repositories/environment.repository.ts
  src/packages/@app/repositories/tab.repository.ts
  src/packages/@app/repositories/testflow.repository.ts
  src/packages/@workspaces/features/environment-explorer/layout/EnvironmentExplorer.svelte
Labels: bug

#1781 fix: fixed import of upvote
  package.json
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
Labels: bug

#1788 Update README.md
  README.md
Labels: documentation

#1794 Docs/update packages readme
  apps/@sparrow-desktop/README.md
  apps/@sparrow-web/README.md
  packages/@sparrow-common/README.md
  packages/@sparrow-library/README.md
  packages/@sparrow-support/README.md
  packages/@sparrow-teams/README.md
  packages/@sparrow-workspaces/README.md
Labels: documentation

#1798 feat: integrate web teams with compatibility to desktop
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-teams/package.json
  packages/@sparrow-teams/src/features/index.ts
  packages/@sparrow-teams/src/features/list-team-navigation/components/index.ts
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-naigation/TeamNavigation.svelte
  packages/@sparrow-teams/src/features/list-team-navigation/index.ts
  packages/@sparrow-teams/src/features/list-team-navigation/layout/ListTeamNavigation.svelte
  packages/@sparrow-teams/src/features/team-list/index.ts
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
Labels: story

#1809 feat: implement auth navigation and teams dropdown
  apps/@sparrow-web/src/components/App.svelte
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: story

#1813 fix: env example sample data
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
Labels: story

#1812 Feat: Added create team Popup
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/features/create-team/components/file-type/FileType.svelte
  packages/@sparrow-common/src/features/create-team/components/icon-uploader/IconUploader.svelte
  packages/@sparrow-common/src/features/create-team/components/index.ts
  packages/@sparrow-common/src/features/create-team/components/team-actions/TeamActions.svelte
  packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte
  packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
  packages/@sparrow-common/src/features/create-team/constants/description.ts
  packages/@sparrow-common/src/features/create-team/constants/icon.ts
  packages/@sparrow-common/src/features/create-team/constants/index.ts
  packages/@sparrow-common/src/features/create-team/constants/name.ts
  packages/@sparrow-common/src/features/create-team/index.ts
  packages/@sparrow-common/src/features/create-team/layout/CreateTeam.svelte
  packages/@sparrow-common/src/features/create-team/types/form.ts
  packages/@sparrow-common/src/features/create-team/types/index.ts
  packages/@sparrow-common/src/features/index.ts
  packages/@sparrow-teams/src/features/index.ts
Labels: story

#1815 Feat/1548/implement auth navigation and teams dropdown
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-naigation/TeamNavigation.svelte
Labels: design

#1817 fix: UI for teams explorer [#1548]
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/team-navigator/TeamNavigator.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: design

#1816 Feat: Added tour guide test flow [#1641]
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/pulse-circle/PulseCircle.svelte
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-workspaces/src/components/index.ts
  packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
  packages/@sparrow-workspaces/src/components/test-flow-tour-guide/TestFlowTourGuide.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/stores/guide.tour.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: story

#1824 fix: fixed a logic issue in opening select dropdown [#1644]
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: bug

#1828 Feat/1548/implement auth navigation and teams dropdown
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: design

#1836 Fix: Added test flow tour guide [#1641]
  packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: story

#1835 feat: handle redirect for web app
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
Labels: enhancement

#1841 fix: Added Pulse effect in tour guide
  packages/@sparrow-common/src/components/pulse-circle/PulseCircle.svelte
Labels: bug

#1842 feat: handle redirect for web app
  apps/@sparrow-web/src/components/App.ts
Labels: enhancement

#1797 Feature: Web app workspace flow
  apps/@sparrow-desktop/src/components/App.svelte
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/store/deviceSync.store.ts
  apps/@sparrow-desktop/src/utils/deeplink/app.deeplink.ts
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  packages/@sparrow-common/src/features/download-app/DownloadApp.svelte
  packages/@sparrow-common/src/features/download-app/icons/DownloadIconWeb.svg
  packages/@sparrow-common/src/features/download-app/index.ts
  packages/@sparrow-common/src/features/index.ts
  packages/@sparrow-teams/src/compopnents/rows/Rows.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/team-navigator/TeamNavigator.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: bug, enhancement, story, front end

#1837 fix: fixed some bugs in creating a new team
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
  packages/@sparrow-common/src/utils/OSDetector.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
Labels: bug

#1863 fix: solved ui bugs []
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  packages/@sparrow-library/src/ui/toast/Toast.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/Profile.svelte
  packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
Labels: bug

#1871 Fix/1833/fix teams and workspaces overflow UI
  apps/@sparrow-web/src/components/App.ts
  packages/@sparrow-library/src/forms/multi-select/MultiSelect.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
Labels: bug

#1847 Feat: Added sample api for test flow [#1642]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1870 fix: fixed issues in tour guide [#1848]
  apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/login-page.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  packages/@sparrow-workspaces/src/components/test-flow-tour-guide/TestFlowTourGuide.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/stores/guide.tour.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: bug

#1879 Fix: Fixed issue in sample api
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: bug

#1883 fix: sparrow initial loading to UI
  apps/@sparrow-web/index.html
  apps/@sparrow-web/src/icons/spin.svg
Labels: bug

#1874 fix: text color related issue
  packages/@sparrow-library/src/icons/ArrowForward.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/compopnents/menu-view/MenuView.svelte
  packages/@sparrow-teams/src/compopnents/rows/Rows.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
Labels: improvement

#1886 fix: fixed issue in first time tour guide start
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#1885 fix: ui and default api on register issue []
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
Labels: bug

#1888 fix: Fixed ui issues
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
Labels: bug

#1894 fix: added fav icon on web app [#1852]
  apps/@sparrow-web/index.html
  apps/@sparrow-web/src/icons/sparrow-favicon.svg
Labels: bug

#1789 feat: Added Go to Desktop Button & Functionality [#1549]
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/features/download-app/DownloadApp.svelte
  packages/@sparrow-library/src/icons/MacIcon.svelte
  packages/@sparrow-library/src/icons/WindowsIcon.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
Labels: story

#1901 fix: add throttler to deeplink redirect rule
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/utils/jwt.ts
Labels: bug

#1904 fix: teams and workspaces UI
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-teams/src/compopnents/menu-view/MenuView.svelte
  packages/@sparrow-teams/src/compopnents/rows/Rows.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: bug

#1918 fix: environment render conditions
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
Labels: bug

#1922 Feat: implement socket io backend api integration
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-desktop/src/services/testflow.service.ts
  apps/@sparrow-desktop/src/services/user.service.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-desktop/src/types/http-client.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/services/user.service.ts
  apps/@sparrow-web/src/services/workspace.service.ts
  apps/@sparrow-web/src/types/http-client.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/types/http-client/client.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/collection-dto.ts
  packages/@sparrow-common/src/types/workspace/folder-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-dto.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-base.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-dto.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/types/workspace/websocket-request-dto.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/index.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: enhancement

#1925 feat: implement socket io template
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-workspaces/package.json
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/RequestMessage.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-name/RequestName.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-parameters/RequestParameters.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview/ResponsePreview.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/store/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/store/socketio.ts
Labels: story

#1927 feat: implement socket io template
  apps/@sparrow-desktop/src/adapter/socket-io-tab.ts
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-workspaces/src/features/save-as-request/components/file-type/FileType.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: story
