Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-06, with the labels that each got.

#1026 feat: revamp save as request
  .github/CODEOWNERS
  src/packages/@app/styles/style.scss
  src/packages/@deprecate/components/file-types/FileType.svelte
  src/packages/@library/icons/Collection.svelte
  src/packages/@library/icons/Folder2.svelte
  src/packages/@library/icons/Workspace.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/button/Button.svelte
  src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
Labels: design

#1027 feat: added feature switch []
  src/packages/@app/database/database.ts
  src/packages/@app/models/feature-switch.model.ts
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/repositories/feature-switch.repository.ts
  src/packages/@app/services/feature-switch.service.ts
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
Labels: front end

#1042 Feat: revamp import collection
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@workspaces/features/import-collection/components/Drop/Drop.svelte
  src/packages/@workspaces/features/import-collection/components/index.ts
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
Labels: design

#1032 fix : fixed the ui issue in tabs in collection tab bar [123]
  src/packages/@app/styles/style.scss
  src/packages/@workspaces/features/tab-bar/components/tab/Tab.svelte
Labels: UI

#1077 Feat/welcome guide popover and carousel
  src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
  src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
  src/packages/@library/ui/carousel/Carousel.svelte
  src/packages/@library/ui/popover/Popover.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
Labels: bug

#1092 fix: fixed ui bugs sprint 1 [123]
  src/packages/@app/styles/style.scss
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
Labels: bug

#1094 fix: fix bugs and updated version
  package.json
  src-tauri/tauri.conf.json
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
  src/packages/@deprecate/components/file-types/FileType.svelte
  src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/import-curl/layout/ImportCurl.svelte
  src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug, front end

#1101 fix: import curl save and over lap issue []
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte
Labels: bug

#1135 fix: added cdn based gifs []
  .env.example
  src/packages/@deprecate/utils/constants.ts
  src/packages/@environments/common/constants/environmentGifs.constants.ts
  src/packages/@environments/common/constants/index.ts
  src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
  src/packages/@library/ui/carousel/Carousel.svelte
  src/packages/@workspaces/common/constants/collectionGifs.constants.ts
  src/packages/@workspaces/common/constants/index.ts
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte
Labels: bug, front end

#1128 fix: fix overlap, and guest user bugs []
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte
Labels: bug

#1136 Feat: Added Bulk Edit feature
  src/packages/@app/database/database.ts
  src/packages/@app/models/tab.model.ts
  src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
  src/packages/@app/repositories/tab.repository.ts
  src/packages/@app/styles/style.scss
  src/packages/@common/types/workspace/request.ts
  src/packages/@common/utils/init-request-tab.ts
  src/packages/@deprecate/components/Modal/AutoUpdateDialog.svelte
  src/packages/@library/forms/SliderSwitch/SliderSwitch.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-parameters/RequestParameters.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
Labels: story

#1142 Fix: the app height to be dynamic in multiple components.
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Dashboard/Dashboard.svelte
  src/packages/@app/pages/EnvironmentPage/EnvironmentPage.svelte
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@common/components/sidebar/Sidebar.svelte
  src/packages/@environments/features/environment-explorer/components/quick-help/QuickHelp.svelte
  src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
  src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@library/ui/list/List.svelte
  src/packages/@support/features/discord-post/layout/DiscordPost.svelte
  src/packages/@support/features/feedback-toast/layout/FeedbackToast.svelte
  src/packages/@support/features/update-toast/layout/UpdateToast.svelte
  src/packages/@support/features/update-toast/layout/index.ts
  src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-auth/RequestAuth.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/RequestBody.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/form-data/FormData.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/none/None.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/raw/Raw.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-parameters/RequestParameters.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body/ResponseBody.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-headers/ResponseHeaders.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: bug, design

#1143 Fix : fixed scrollbar UI
  src/packages/@app/styles/style.scss
Labels: bug
