Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-11, with the labels that each got.

#1928 Feat/implement socket io save as feature
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: story

#1929 fix: workspace regression issues
  apps/@sparrow-desktop/src/styles/style.scss
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug, design

#1931 fix: Replace web socket icon with socket io
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
Labels: bug

#1930 feat: Udpated the UI part for socket-io header [#1893]
  apps/@sparrow-desktop/src/styles/style.scss
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
Labels: story

#1934 Fix: Sync tabular input with form data in desktop.
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Labels: design

#1935 Fix: UI for tabular input
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Labels: design

#1936 Feat: Added request event navigator [#1890]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/events-lists/RequestEventsList.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-events/RequestEvents.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
Labels: story

#1916 fix: fixed issue in workspace page [#1840]
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
Labels: bug

#1950 Feat : Socket.io Message Request Navigator
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/RequestMessage.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
Labels: story

#1948 fix: added Event Saving function of event data in backend database [#1890]
  apps/@sparrow-desktop/src/adapter/socket-io-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
Labels: story

#1953 Fix: Fixed workspace search issue and Event name bug
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-events/RequestEvents.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: bug

#1955 fix: Added socket io Filter Functionality [#1881]
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
Labels: story

#1951 refactor: implement improved toast message
  packages/@sparrow-library/src/ui/toast/Toast.svelte
  packages/@sparrow-library/src/ui/toast/icons/error.svelte
  packages/@sparrow-library/src/ui/toast/icons/success.svelte
Labels: design

#1954 fix : Request name backendsync
  apps/@sparrow-desktop/src/adapter/socket-io-tab.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
Labels: story

#1956 Feat/socket io connection implementation
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/repositories/tab.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview/ResponsePreview.svelte
Labels: story

#1940 fix: workspace and teams deletion on web app
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  apps/@sparrow-web/src/repositories/team.repository.ts
  apps/@sparrow-web/src/repositories/workspace.repository.ts
Labels: bug

#1957 feat: added mixpanel events and fixed namespace error issue in rust []
  apps/@sparrow-desktop/src-tauri/src/main.rs
  packages/@sparrow-common/src/enums/mixpanel-events.enum.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: bug

#1966 fix: socket io UI
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-library/src/icons/Download2.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/socket-explorer/components/request-body/sub-body/request-body-navigator/SocketMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
Labels: bug

#1974 fix: download and copy button on web socket
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
Labels: bug

#1979 fix: package version upgrade
  apps/@sparrow-desktop/package.json
  package.json
Labels: bug

#2001 fix: multiple api calls for teams and collaboration [#1960] [#1805]
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/utils/jwt.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/utils/jwt.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-common/src/utils/sleep.ts
Labels: bug

#2003 fix: delay web app render by 2 sec on load to fetch essential app data
  apps/@sparrow-web/index.html
Labels: enhancement

#2004 fix: resolve-testflow-ui-issues
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/testflow.service.ts
  packages/@sparrow-common/src/utils/init-testflow-tab.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug, design

#1937 Fix: Fixed help module issues [#1851]
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.ViewModel.ts
  packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
  packages/@sparrow-support/src/features/add-feedback/layout/AddFeedback.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackPost.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
  packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte
Labels: bug

#2010 Fix: Fixed issues in teams and workspaces [#1723]
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/forms/select/menu-items/MenuItemsv2.svelte
  packages/@sparrow-teams/src/compopnents/file-type/FileType.svelte
  packages/@sparrow-teams/src/compopnents/index.ts
  packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/Profile.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
Labels: bug

#2015 fix: Fixed Regression issues [#1801]
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/store/websocket.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
Labels: bug

#2016 fix: fixed no result found message missing on searching member [#253]
  packages/@sparrow-teams/src/features/workspace-members/layout/WorkspaceMembers.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
Labels: bug

#2019 feat: added send graphql function in RPC []
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src/containers/api/api.common.ts
Labels: feature

#2023 fix: handle socket io message event receiver
  apps/@sparrow-desktop/src-tauri/gen/schemas/windows-schema.json
  apps/@sparrow-desktop/src/containers/api/api.common.ts
Labels: bug

#2034 fix: fixed ui of header [#1994]
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
Labels: bug

#2049 fix: fixed navigator ui all over the request and response
  packages/@sparrow-workspaces/src/components/index.ts
  packages/@sparrow-workspaces/src/components/navigator/Navigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/socket-navigator/SocketNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-navigator/RequestNavigatorTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#2051 feat: added hoc for copy and download requests [#1985]
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/hoc/WithButtonV6.svelte
  packages/@sparrow-workspaces/src/hoc/index.ts
Labels: enhancement

#2054 fix: message event listener for socket io
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
Labels: bug

#2056 fix: fixed bugs mentioned in [#2044] [#2045] [#2047] [#2040]
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte
Labels: bug

#2060 Feat/1993/implement graphql save as feature
  apps/@sparrow-desktop/src/adapter/graphql-tab.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-base.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-dto.ts
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: story

#2057 Feat: Added mix panel events for graphql [#1996]
  packages/@sparrow-common/src/enums/mixpanel-events.enum.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: story

#2059 fix: fixed recent api , add restriction to five api only [#2042]
  packages/@sparrow-teams/src/features/recent-apis/layout/RecentApi.svelte
Labels: bug

#2063 fix: update workspace access permission to team member [#1961]
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
Labels: bug

#2064 fix: save graphql request bugs [#1993]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug

#2066 fix: dropdown v2 overflow and graphQL keyboard shortcuts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/forms/select/menu-items/MenuItemsv2.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/utils/decode-graphql.ts
Labels: bug

#2067 feat: added websocket auto-disconnection []
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: bug, front end

#2072 fix: codemirror input code handler
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
Labels: bug

#2071 fix: Fixed Ellipsis missing on searching workspaces.
  packages/@sparrow-library/src/forms/select/menu-items/MenuItemsV3.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#2074 fix: teams and collaboration ui bugs
  packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
  packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: design

#2104 fix: teams and collaboration ui bugs
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  packages/@sparrow-library/src/ui/popover/Popover.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/socket-headers/SocketHeaders.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#2075 fix: fixed bugs from loop doc of sep 16 to sep 20
  packages/@sparrow-common/src/components/sidebar/Sidebar.svelte
  packages/@sparrow-library/src/forms/select/menu-items/MenuItemsV3.svelte
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
Labels: bug

#2116 feat: added the REST API in Web App []
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/index.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/repositories/environment.repository.ts
  apps/@sparrow-web/src/repositories/tab.repository.ts
  apps/@sparrow-web/src/services/ai-assistant.service.ts
  apps/@sparrow-web/src/services/collection.service.ts
  apps/@sparrow-web/src/services/collection.ts
  apps/@sparrow-web/src/services/testflow.service.ts
  apps/@sparrow-web/src/services/updates.service.ts
  apps/@sparrow-web/src/store/deviceSync.store.ts
  apps/@sparrow-web/src/types/http-client.ts
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/sidebar/Sidebar.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: feature

#2123 feat: completed ui and the value get stored up in local storage
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-library/src/icons/CheckCircle.svelte
  packages/@sparrow-library/src/icons/index.ts
Labels: front end

#2138 fix: add search behaviour with lowercase [#2079]
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/hoc/WithSelect.svelte
Labels: story
