Repository sparrowapp-dev/sparrow-app, pull requests merged in 2024-09, with the labels that each got.

#1474 fix: local collection imports
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@common/components/header/Header.svelte
Labels: bug

#1503 feat: Merge development into canny
  .github/workflows/development.yaml
  src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/styles/style.scss
  src/packages/@common/components/header/Header.svelte
  src/packages/@deprecate/assets/save.svelte
  src/packages/@library/icons/Tick.svelte
  src/packages/@library/icons/index.ts
  src/packages/@library/ui/button/Button.svelte
  src/packages/@library/ui/tooltip/Tooltip.svelte
  src/packages/@workspaces/features/chat-bot/assests/Tick.svg
  src/packages/@workspaces/features/chat-bot/assests/index.ts
  src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  src/packages/@workspaces/features/chat-bot/components/ai-suggestion-box/AISuggestionBox.svelte
  src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
  src/packages/@workspaces/features/chat-bot/components/prompt-input/PromptInput.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body/ResponseBody.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: devops

#1510 feat: add request block to testflow canvas [#1442]
  src/packages/@library/icons/PlayArrow.svelte
  src/packages/@library/icons/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
  src/packages/@workspaces/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: story

#1504 refactor: delete workspace items operations on team leave
  src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  src/packages/@app/repositories/team.repository.ts
  src/packages/@app/repositories/workspace.repository.ts
  src/packages/@app/services/team.service.ts
Labels: improvement

#1514 Fix/unlink unused imports from deprecate component
  src/packages/@app/components/App.svelte
  src/packages/@app/pages/Auth/forgot-password/ForgotPassword.svelte
  src/packages/@app/pages/Auth/login-page/LoginPage.svelte
  src/packages/@app/pages/Auth/login-page/login-page.ts
  src/packages/@app/pages/Auth/register-page/RegisterPage.svelte
  src/packages/@app/pages/Auth/reset-password/ResetPassword.svelte
  src/packages/@app/pages/Auth/update-password/UpdatePassword.svelte
  src/packages/@app/pages/Collections/Collections.ViewModel.old.ts
  src/packages/@app/pages/Collections/Collections.old.svelte
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
  src/packages/@app/pages/Dashboard/Dashboard.old.svelte
  src/packages/@app/pages/Home/home-page/HomePage.svelte
  src/packages/@app/pages/Teams/Teams.old.svelte
  src/packages/@app/utils/index.ts
  src/packages/@app/utils/window-resize.ts
  src/packages/@common/features/app-updater/index.ts
  src/packages/@common/features/app-updater/layout/AppUpdater.svelte
  src/packages/@common/features/index.ts
  src/packages/@deprecate/api/api.common.ts
  src/packages/@deprecate/utils/sample/workspace.sample.ts
  src/packages/@workspaces/common/components/combo-text/ComboText.svelte
  src/packages/@workspaces/common/components/drop-button/DropButton.svelte
  src/packages/@workspaces/common/components/index.ts
  src/packages/@workspaces/common/hoc/WithModal.svelte
  src/packages/@workspaces/common/hoc/index.ts
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-name/RequestName.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-pane/RequestPane.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-pane/ResponsePane.svelte
  src/packages/@workspaces/features/rest-explorer/components/rest-extension-panel/RestExtensionPanel.svelte
  src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
  src/packages/@workspaces/features/save-as-request/components/file-type/FileType.svelte
  src/packages/@workspaces/features/save-as-request/components/index.ts
  src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
  src/packages/@workspaces/features/save-as-request/utils/index.ts
  src/packages/@workspaces/features/save-as-request/utils/search-collection-item.ts
  src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/socket-explorer/components/response-pane/ResponsePane.svelte
  src/packages/@workspaces/features/socket-explorer/components/socket-name/SocketName.svelte
  src/packages/@workspaces/features/socket-explorer/components/socket-pane/SocketPane.svelte
Labels: enhancement

#1523 fix: http request creation from folder module
  src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
Labels: bug

#1525 feat: saving testflow data to local database [#1442]
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@common/types/workspace/testflow.ts
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1505 Feat: Added filter functionality in feedback [#1439]
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/services/canny.service.ts
  src/packages/@support/common/types/feedback.ts
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
Labels: story

#1530 fix: fixed app crash []
  src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: bug

#1531 feat: added base url for web socket []
  .env.example
  .github/workflows/development.yaml
  .github/workflows/release.yaml
  src/packages/@app/services/ai-assistant.ws.service.ts
  src/packages/@deprecate/utils/constants.ts
Labels: bug

#1537 fix: text editor string parsing issue in the docs section [#1506]
  src/packages/@app/pages/Auth/redirect/Redirect.svelte
  src/packages/@library/forms/text-editor/TextEditor.svelte
  src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
Labels: bug

#1539 fix: fixed base env in workflow []
  .github/workflows/development.yaml
  .github/workflows/release.yaml
Labels: bug

#1540 Fix: Adjust Environment Permissions for Viewer Role
  src/packages/@app/styles/style.scss
  src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte
  src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
  src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#1555 fix: handle query params for curl [#1513]
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
Labels: bug

#1563 Feat/implement activity section
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/services/canny.service.ts
  src/packages/@library/ui/like/Like.svelte
  src/packages/@library/ui/like/index.ts
  src/packages/@support/common/types/activity.ts
  src/packages/@support/features/activity-section/index.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/activity-section/layout/index.ts
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: bug

#1579 Fix: Refactored Complete Help Page Code
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/styles/style.scss
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/common/components/Upvote.svelte
  src/packages/@support/common/types/feedback.ts
  src/packages/@support/common/utils/formatTimeAgo.ts
  src/packages/@support/common/utils/index.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: bug

#1583 fix: added env in testflow run
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: bug

#1584 Feat/implement run history flow
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@app/styles/style.scss
  src/packages/@common/utils/formatTime.ts
  src/packages/@common/utils/index.ts
  src/packages/@library/icons/Check2.svelte
  src/packages/@library/icons/Exclamation.svelte
  src/packages/@library/icons/History.svelte
  src/packages/@library/icons/index.ts
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/common/components/Upvote.svelte
  src/packages/@support/common/types/feedback.ts
  src/packages/@support/common/utils/index.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
  src/packages/@workspaces/common/hoc/WithButtonV5.svelte
  src/packages/@workspaces/common/hoc/index.ts
  src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/socket-explorer/store/testflow.ts
  src/packages/@workspaces/features/testflow-explorer/components/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/run-history/RunHistory.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: story

#1588 Feat: start block add option bug
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#1591 fix: added run txt []
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/icons/Info.svelte
  src/packages/@workspaces/features/testflow-explorer/icons/index.ts
Labels: bug

#1580 Fix : Updated My Activity Section
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/styles/style.scss
  src/packages/@library/icons/TableChart.svelte
  src/packages/@library/icons/index.ts
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/common/components/HelpInfo-Card/HelpInfoCard.svelte
  src/packages/@support/common/components/Upvote.svelte
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
  src/packages/@support/features/community/layout/Community.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackDefault.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: story

#1592 Feat: add api block
  src/packages/@library/icons/ArrowRight.svelte
  src/packages/@library/icons/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/icons/ArrowSolid.svelte
  src/packages/@workspaces/features/testflow-explorer/icons/index.ts
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1593 fix: run flow enhancements [#1400]
  src/packages/@library/icons/Run.svelte
  src/packages/@library/icons/index.ts
  src/packages/@workspaces/common/components/drop-button/DropButton.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#1596 feat: handle request color on run testflow [#1446]
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@library/icons/clock.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-status/ResponseStatus.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1598 fix: ui issues for testflow [#1446]
  src/packages/@workspaces/common/components/drop-button/DropButton.svelte
  src/packages/@workspaces/common/hoc/WithButtonV5.svelte
  src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: design

#1597 Feat: Added Run Test flow with request 1501
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/styles/style.scss
  src/packages/@library/icons/ArrowSplit.svelte
  src/packages/@library/icons/index.ts
  src/packages/@workspaces/common/components/index.ts
  src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
  src/packages/@workspaces/common/components/table-sidebar/TableSidebar.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
  src/packages/@workspaces/features/socket-explorer/store/testflow.ts
  src/packages/@workspaces/features/testflow-explorer/components/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/binary/Binary.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/form-data/FormData.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/none/None.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/raw/Raw.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-navigator/RequestNavigatorTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1607 Feat/implement testflow response data integration
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@common/utils/init-testflow-tab.ts
  src/packages/@deprecate/components/collections/req-res-section/sub-components/request-header-section/Headers.svelte
  src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
  src/packages/@workspaces/common/components/table-sidebar/TableSidebar.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
  src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte
  src/packages/@workspaces/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  src/packages/@workspaces/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  src/packages/@workspaces/features/socket-explorer/components/socket-headers/SocketHeaders.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/form-data/FormData.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/raw/Raw.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
  src/packages/@workspaces/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1619 feat: add redirect rule for request navigation [#1446]
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
  src/packages/@workspaces/common/components/table-sidebar/TableSidebar.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1606 Feat: Added mix panel in Help Section [#1499]
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@deprecate/utils/enums/mixpanel-events.enum.ts
  src/packages/@support/common/components/CommentCard.svelte
  src/packages/@support/common/components/HelpInfo-Card/HelpInfoCard.svelte
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackDefault.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: story

#1605 Fix: Fixed button alignment in the carousel [#1536]
  src/packages/@library/ui/carousel/Carousel.svelte
Labels: bug

#1603 fix: Fixed WebSocket name issue [#1517]
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@common/types/workspace/web-socket.ts
  src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
  src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
  src/packages/@workspaces/features/collection-list/components/web-socket/WebSocket.svelte
Labels: bug

#1623 feat: implement backend integration on create, delete and fetch testf…
  src/packages/@app/pages/Collections/CollectionsPage.svelte
  src/packages/@app/pages/Collections/Testflow.ViewModel.ts
  src/packages/@app/repositories/testflow.repository.ts
  src/packages/@app/services/testflow.service.ts
  src/packages/@common/utils/init-testflow-tab.ts
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
Labels: story

#1624 feat: testflow lists to render according to workspace switch [#1446]
  src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
  src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte
Labels: story

#1640 feat: add save as ui [#1533]
  src/packages/@common/components/header/sub-component/UserProfileModal.svelte
  src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  src/packages/@workspaces/features/testflow-explorer/components/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/run-history/RunHistory.svelte
  src/packages/@workspaces/features/testflow-explorer/components/save-testflow/SaveTestflow.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1625 Feat/added edit test flow name
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@app/repositories/testflow.repository.ts
  src/packages/@workspaces/features/testflow-explorer/components/index.ts
  src/packages/@workspaces/features/testflow-explorer/components/test-flow-name/TestFlowName.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1643 fix: sync nodes data with collection list []
  src/packages/@app/repositories/tab.repository.ts
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#1601 feat: Added delete functionality of test flow Node [#1402]
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@workspaces/common/components/delete-node/DeleteNode.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1650 fix: resolved comments [#1402]
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#1604 fix: Fixed P-2 Bugs in Help Section [#1575]
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: bug

#1653 fix: connected nodes with the observable for real time data change
  src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
  src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#1655 feat: implement drag and drop on request block testflow
  src/packages/@library/icons/Drop.svelte
  src/packages/@library/icons/index.ts
  src/packages/@workspaces/features/collection-list/components/request/Request.svelte
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1656 Feat/implement run testflow on start block
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#1657 fix: disable edge drag from nodes
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
Labels: bug

#1659 Fix: Fixed some bug in testflows
  src/packages/@workspaces/common/components/delete-node/DeleteNode.svelte
  src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
  src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
  src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
Labels: bug

#1665 feat: add drag at start block [#1398]
  src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
  src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
Labels: story

#1658 feat: Added edit post functionaltiy [#1578]
  src/packages/@app/pages/Help/HelpPage.ViewModel.ts
  src/packages/@app/pages/Help/HelpPage.svelte
  src/packages/@app/services/canny.service.ts
  src/packages/@support/common/components/Drop/Drop.svelte
  src/packages/@support/common/components/Upvote.svelte
  src/packages/@support/common/components/index.ts
  src/packages/@support/features/activity-section/layout/ActivitySection.svelte
  src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
Labels: story

#1667 fix: fixed name in default page [#123]
  src/packages/@workspaces/features/testflow-explorer/components/run-history/RunHistory.svelte
  src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: bug

#1668 fix: fixed undefined issue in activity section [#123]
  src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
  src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
Labels: bug

#1670 fix: Fixed some general issue
  src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
  src/packages/@support/features/roadmap/layout/Roadmap.svelte
Labels: bug

#1672 feat: Upgraded Sparrow to V2.8.0 []
  package.json
  src-tauri/tauri.conf.json
Labels: front end

#1679 fix: add run scripts to package json
  package.json
Labels: story

#1680 fix: web imports
  apps/@sparrow-web/vite.config.ts
Labels: story

#1681 Feat: add web app packages dependencies to the app
  apps/@sparrow-desktop/package.json
  apps/@sparrow-web/package.json
  apps/@sparrow-web/src/App.svelte
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-workspaces/package.json
Labels: story

#1688 Feat/refactor web setup
  packages/@sparrow-deprecate/src/assets/DownArrow.svelte
  packages/@sparrow-deprecate/src/assets/app.asset.ts
  packages/@sparrow-deprecate/src/assets/arrow/DownArrow.svelte
  packages/@sparrow-deprecate/src/assets/arrow/index.ts
  packages/@sparrow-deprecate/src/assets/git-branch.svelte
  packages/@sparrow-deprecate/src/assets/icons/index.ts
  packages/@sparrow-deprecate/src/assets/icons/search.svelte
  packages/@sparrow-deprecate/src/assets/index.ts
  packages/@sparrow-deprecate/src/assets/pen.svelte
  packages/@sparrow-deprecate/src/assets/reload-collection.svelte
  packages/@sparrow-deprecate/src/assets/search.svelte
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/ui/dragdrop/DragDrop.svelte
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackFilters.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackPost.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
  packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
  packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte
  packages/@sparrow-teams/src/compopnents/rows/Rows.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/create-team/components/icon-uploader/IconUploader.svelte
  packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/import-collection/components/Drop/Drop.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
Labels: story
