Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-03, with the labels that each got.

#2702 Fix/tab splitter direction http request and saved http request
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/hocs/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/hocs/with-button.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/hocs/with-select.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/layout/RestExplorerSaved.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/store/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/store/rest-explorer.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/store/splitpanes.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/types/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/types/request.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/store/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/store/splitpanes.ts
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/stores/index.ts
  packages/@sparrow-workspaces/src/stores/tabs-view.ts
Labels: bug

#2691 fix: Test Flow card name overflow and color issue.
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: bug

#2695 fix: Made the testflow start button disabled when no api request bloc…
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
Labels: bug

#2704 feat: added save api response in sparrow edge in app [SPRW-316]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: front end, feature

#2698 fix: [Teams & Workspace] As a Viewer, User should not be able to see edit popup.
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
Labels: bug

#2694 fix: fixed the toast message on disconnect for socket and websocket […
  apps/@sparrow-web/src/containers/api/api.common.ts
Labels: bug

#2703 LHS popup alignment fix [#102]
  packages/@sparrow-library/src/ui/options/Options.svelte
Labels: bug

#2690 bugs : fixing
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-library/src/icons/GlobeRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/button/Button.svelte
  packages/@sparrow-teams/src/components/api-list-items/ApiListItem.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#2712 Feat/implement collection level auth
  apps/@sparrow-desktop/src/adapter/collection-tab.ts
  apps/@sparrow-desktop/src/adapter/index.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/dto/collection.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/collection-tab.ts
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-common/src/utils/init-collection-tab.ts
  packages/@sparrow-common/src/utils/init-saved-request.ts
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/CollectionAuth.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/index.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/no-auth/NoAuth.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-navigator/CollectionNavigator.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: story

#2739 Ai-chat-bot
  packages/@sparrow-common/src/icons/SparkleFilled.svelte
Labels: task

#2720 Feat/implement collection level auth
  apps/@sparrow-desktop/src/adapter/request-saved-tab.ts
  apps/@sparrow-desktop/src/adapter/request-tab.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  packages/@sparrow-common/src/enums/authorization.enum.ts
  packages/@sparrow-common/src/enums/index.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-saved-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-saved-tab.ts
  packages/@sparrow-common/src/types/workspace/http-request-tab.ts
  packages/@sparrow-common/src/utils/auth.helper.ts
  packages/@sparrow-common/src/utils/init-collection-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-common/src/utils/init-saved-request.ts
  packages/@sparrow-library/src/icons/OpenRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/button/Button.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/CollectionAuth.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/no-auth/NoAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/no-auth/NoAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/layout/RestExplorerSaved.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/no-auth/NoAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/decode-request.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/reduce-auth-header.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/reduce-auth-parameter.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
Labels: task

#2740 bugs : Left panel workspace
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: bug

#2742 feat: duplicate collection level auth to web
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/adapter/collection-tab.ts
  apps/@sparrow-web/src/adapter/index.ts
  apps/@sparrow-web/src/adapter/request-tab.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/RequestAuth.svelte
Labels: task

#2743 feat/card-components
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
Labels: bug

#2741 AI-chat-bot
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
Labels: task

#2747 feat: implement testflows for web and desktop
  apps/@sparrow-desktop/src/adapter/request-tab.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/adapter/request-tab.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/decode-request.ts
Labels: task

#2748 Fix/implement collection level auth testflow run
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/utils/jwt.ts
Labels: bug

#2751 Inline text field outlined
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-teams/src/features/create-workspace/components/workspace-name/WorkspaceName.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
Labels: task

#2708 feat: default Workspace tour guide
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-library/src/icons/DocumentRegular.svelte
  packages/@sparrow-library/src/icons/GiftRegular.svelte
  packages/@sparrow-library/src/icons/QuestionCircleReqular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/components/index.ts
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/welcome-popup/icons/SparrowIconLogo.svelte
  packages/@sparrow-workspaces/src/features/welcome-popup/layout/WelcomePopup.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/components/default-tour-guide/DefaultTourGuide.svelte
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/index.ts
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/layout/WorkspaceTourGuide.svelte
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/utils/index.ts
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/utils/tourGuideContent.ts
  packages/@sparrow-workspaces/src/stores/defaultGuide.tour.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: feature

#2718 Feat: Added tab controls functionality
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/icons/DismissCircleRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: feature

#2745 feat: ds support GraphQL.
  packages/@sparrow-library/src/icons/ArchiveRegular.svelte
  packages/@sparrow-library/src/icons/ArrowClockWiseRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-variables/RequestVariables.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-headers/ResponseHeaders.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/utils/auth-input-theme.ts
Labels: feature

#2758 fix: resolved text moving issue on hover in CodeMirrorInput.
  packages/@sparrow-workspaces/src/utils/url-input-theme.ts
Labels: bug

#2761 fix: saving http requests deletes saved request
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
Labels: bug

#2759 feat/cards-component
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#2755 alert comoponent
  packages/@sparrow-library/src/icons/WarningFilled.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/alert/Alert.svelte
  packages/@sparrow-library/src/ui/alert/index.ts
  packages/@sparrow-library/src/ui/index.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-error-screen/ResponseErrorScreen.svelte
Labels: task

#2768 Feat: Added Inline Text Field Component
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-name/TestFlowName.svelte
Labels: feature

#2780 fix: default Tour guide starting flow after loading Items.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/welcome-popup/layout/WelcomePopup.svelte
Labels: bug

#2782 fix: resolved issue with redirecting
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
Labels: bug

#2783 fix: resolved ui issues in Ds support Graphql
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
Labels: bug

#2786 fix: fixed the typos for notifications messages
  apps/@sparrow-web/src/containers/api/api.common.ts
Labels: bug

#2785 fix: updated the button name on the Welcome card
  packages/@sparrow-workspaces/src/features/welcome-popup/layout/WelcomePopup.svelte
Labels: bug

#2787 fix: auth navigation unsaved changes and collection level auth rerfresh
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
Labels: bug

#2737 Updated the --bug-report.yaml to include other fields
  .github/ISSUE_TEMPLATE/--bug-report.yaml
Labels: pull request

#2738 Updated the --feature-request.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: pull request

#2789 Fix: position issue of Test flow Tour Guide card.
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#2794 fix: fixed the wrong block count in the delete popup in testflows
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#2795 Transform issues created in GITHUB to JIRA
  .github/workflows/github-to-jira.yml
Labels: pull request

#2796 Fix: Environment should be de-selected once user check that radio button.
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
Labels: bug

#2802 Bugs in left work space
  packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
  packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
  packages/@sparrow-library/src/forms/checkbox/Checkbox.svelte
  packages/@sparrow-library/src/icons/SaveRegular.svelte
  packages/@sparrow-library/src/ui/alert/Alert.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/events-lists/RequestEventsList.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#2746 Feat/suport teams setting
  packages/@sparrow-library/src/icons/ArrowUploadFilled.svelte
  packages/@sparrow-library/src/icons/EditRegular.svelte
  packages/@sparrow-library/src/icons/LockClosedRegular.svelte
  packages/@sparrow-library/src/icons/SearchFilled.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/features/team-settings/components/settings-navigator/SettingsNavigator.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/team-owner/TeamOwner.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
  packages/@sparrow-teams/src/features/team-settings/layout/TeamSettings.svelte
Labels: task

#2757 Update/members workspace
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/icons/CaretDownRegular.svelte
  packages/@sparrow-library/src/icons/ListRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/Profile.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
Labels: task

#2803 feat: Improve search in code editor
  packages/@sparrow-library/src/forms/editor/theme.ts
Labels: feature

#2807 Updated the github-to-jira.yml file with few changes
  .github/workflows/github-to-jira.yml
Labels: pull request

#2812 updates in left workspace panel
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
Labels: bug

#2750 Feat/lovekesh teams workspace
  packages/@sparrow-common/src/features/create-team/components/icon-uploader/IconUploader.svelte
  packages/@sparrow-common/src/features/create-team/components/team-actions/TeamActions.svelte
  packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte
  packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
  packages/@sparrow-common/src/features/create-team/constants/description.ts
  packages/@sparrow-common/src/features/create-team/constants/icon.ts
  packages/@sparrow-common/src/features/create-team/constants/name.ts
  packages/@sparrow-common/src/icons/SparrowLogo.svelte
  packages/@sparrow-common/src/icons/index.ts
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-library/src/forms/textarea/Textarea.svelte
  packages/@sparrow-library/src/icons/ChevronLeftRegular.svelte
  packages/@sparrow-library/src/icons/CloudArrowUpRegular.svelte
  packages/@sparrow-library/src/icons/ImageRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/components/table/Table.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
Labels: task

#2815 Implentation ctrl z ctrl y
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
Labels: task

#2816 try button is not working in global enviroment variable case
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: bug

#2820 docs: update PR template
  .github/workflows/pull_request_template.md
  docs/pull_request_template.md
Labels: pr-doc, pr-build

#2821 feat: added dynamic error messages for failure cases [SPRW-395]
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-error-screen/ResponseErrorScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-feature

#2817 feat: implement abort controller for socketio and websockets
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
  packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/store/websocket.ts
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: task

#2825 Update --bug-report.yaml
  .github/ISSUE_TEMPLATE/--bug-report.yaml
Labels: pr-refactor

#2826 Update --feature-request.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: pr-refactor

#2827 Update --bug-report.yaml
  .github/ISSUE_TEMPLATE/--bug-report.yaml
Labels: pr-refactor

#2828 Update pull_request_template.md
  .github/workflows/pull_request_template.md
Labels: pr-bugfix

#2793 Resume same progress
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/stores/index.ts
  packages/@sparrow-workspaces/src/stores/recent-left-panel.ts
Labels: task

#2843 Feat/suport teams setting
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
Labels: feature

#2832 fix: typography update
  apps/@sparrow-desktop/src/components/styles.css
  apps/@sparrow-web/src/components/styles.css
  packages/@sparrow-common/src/constants/fonts.constant.ts
  packages/@sparrow-library/src/ui/button/Button.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: pr-style

#2838 fix: pagination issue while search in workspace
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#2823 Sprw 401 storybook deployment 1
  apps/@sparrow-storybook/.storybook/main.js
  apps/@sparrow-storybook/.storybook/preview.js
  apps/@sparrow-storybook/package.json
  apps/@sparrow-storybook/src/stories/Alert.stories.js
  apps/@sparrow-storybook/src/stories/Avatar.stories.js
  apps/@sparrow-storybook/src/stories/Badge.stories.js
  apps/@sparrow-storybook/src/stories/Breadcrumbs.stories.js
  apps/@sparrow-storybook/src/stories/Button.stories.js
  apps/@sparrow-storybook/src/stories/Carousel.stories.js
  apps/@sparrow-storybook/src/stories/Checkbox.stories.js
  apps/@sparrow-storybook/src/stories/Chip.stories.js
  apps/@sparrow-storybook/src/stories/DragDrop.stories.js
  apps/@sparrow-storybook/src/stories/Dropdown.stories.js
  apps/@sparrow-storybook/src/stories/Editor.stories.js
  apps/@sparrow-storybook/src/stories/ImageModal.stories.svelte
  apps/@sparrow-storybook/src/stories/Input.stories.js
  apps/@sparrow-storybook/src/stories/KeyboardShortcut.stories.js
  apps/@sparrow-storybook/src/stories/Loader.stories.js
  apps/@sparrow-storybook/src/stories/MultiSelect.stories.js
  apps/@sparrow-storybook/src/stories/Navigator.stories.js
  apps/@sparrow-storybook/src/stories/Options.stories.js
  apps/@sparrow-storybook/src/stories/Popover.stories.js
  apps/@sparrow-storybook/src/stories/Progress.stories.js
  apps/@sparrow-storybook/src/stories/Radio.stories.js
  apps/@sparrow-storybook/src/stories/Tags.stories.js
  apps/@sparrow-storybook/src/stories/TextArea.stories.js
  apps/@sparrow-storybook/src/stories/TextEditor.stories.js
  apps/@sparrow-storybook/src/stories/Toggle.stories.js
  apps/@sparrow-storybook/src/stories/Tooltip.stories.js
  apps/@sparrow-storybook/yarn.lock
Labels: pr-feature, pr-style

#2810 Feat: Implemented global button loading for http, websocket, socketio.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/store/index.ts
  packages/@sparrow-common/src/store/loading.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
Labels: feature

#2833 Rest ui issues
  packages/@sparrow-library/src/ui/toggle/Toggle.svelte
  packages/@sparrow-workspaces/src/components/missed-environment/MissedEnvironment.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/none/None.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/none/None.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-headers/ResponseHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/hoc/WithSelectV3.svelte
Labels: pr-bugfix

#2830 feat/remove-shortcuts
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/TitleBar.svelte
  packages/@sparrow-library/src/ui/keyboardShortcuts/keyboardShortcuts.svelte
  packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
Labels: task, pr-feature

#2819 feature: Auto Environment Selection on Relaunching/Login App
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: feature, pr-feature

#2846 feat: Implement GraphQL Proxy with Browser Agent for Web Application
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-feature

#2829 Feat/workspace notes
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte
Labels: task

#2811 feat/workspace-auth
  packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: task

#2853 storybook deployment
  apps/@sparrow-storybook/.storybook/main.js
  apps/@sparrow-storybook/.storybook/preview.js
  apps/@sparrow-storybook/package.json
  apps/@sparrow-storybook/src/stories/Alert.stories.js
  apps/@sparrow-storybook/src/stories/Avatar.stories.js
  apps/@sparrow-storybook/src/stories/Badge.stories.js
  apps/@sparrow-storybook/src/stories/Breadcrumbs.stories.js
  apps/@sparrow-storybook/src/stories/Button.stories.js
  apps/@sparrow-storybook/src/stories/Carousel.stories.js
  apps/@sparrow-storybook/src/stories/Checkbox.stories.js
  apps/@sparrow-storybook/src/stories/Chip.stories.js
  apps/@sparrow-storybook/src/stories/DragDrop.stories.js
  apps/@sparrow-storybook/src/stories/Dropdown.stories.js
  apps/@sparrow-storybook/src/stories/Editor.stories.js
  apps/@sparrow-storybook/src/stories/ImageModal.stories.svelte
  apps/@sparrow-storybook/src/stories/Input.stories.js
  apps/@sparrow-storybook/src/stories/KeyboardShortcut.stories.js
  apps/@sparrow-storybook/src/stories/Loader.stories.js
  apps/@sparrow-storybook/src/stories/MultiSelect.stories.js
  apps/@sparrow-storybook/src/stories/Navigator.stories.js
  apps/@sparrow-storybook/src/stories/Options.stories.js
  apps/@sparrow-storybook/src/stories/Popover.stories.js
  apps/@sparrow-storybook/src/stories/Progress.stories.js
  apps/@sparrow-storybook/src/stories/Radio.stories.js
  apps/@sparrow-storybook/src/stories/Tags.stories.js
  apps/@sparrow-storybook/src/stories/TextArea.stories.js
  apps/@sparrow-storybook/src/stories/TextEditor.stories.js
  apps/@sparrow-storybook/src/stories/Toggle.stories.js
  apps/@sparrow-storybook/src/stories/Tooltip.stories.js
  apps/@sparrow-storybook/yarn.lock
Labels: pr-feature

#2677 Fix: Global Search Recent Section Issues & Search Highlighting
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/components/SearchBar/SearchBar.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/ItemBar.svelte
Labels: bug, pr-bugfix

#2854 fix: environment missing issue for saved request
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte
  packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte
  packages/@sparrow-library/src/forms/label-field/LabelField.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte
  packages/@sparrow-workspaces/src/components/missed-environment/MissedEnvironment.svelte
Labels: bug

#2845 Sprw 431 ds UI tabs update
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/components/review-environment/ReviewEnvironment.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/request-body/sub-body/request-body-navigator/SocketMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
Labels: pr-style

#2855 fix: modal cross icon [412]
  packages/@sparrow-library/src/ui/modal/Modal.svelte
Labels: bug

#2824 feat: refresh workspace
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: feature, pr-feature

#2858 feat: added feature to save response body type [SPRW-366]
  apps/@sparrow-desktop/src/adapter/request-saved-tab.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/adapter/request-saved-tab.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  packages/@sparrow-common/src/types/workspace/http-request-saved-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-saved-dto.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/layout/RestExplorerSaved.svelte
Labels: pr-bugfix, pr-feature

#2861 Update in left workspace
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
Labels: pr-bugfix

#2863 fix: graphql save mutation issue for web app
  apps/@sparrow-web/src/adapter/graphql-tab.ts
  apps/@sparrow-web/src/services/collection.service.ts
Labels: bug

#2865 bugs
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-workspaces/src/components/environment-picker/EnvironmentPicker.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#2860 Fix: Code Optimization for Bluk Tab Deletion from LHS
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/tab.repository.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/tab.repository.ts
Labels: pr-refactor

#2866 Update in left workspace
  packages/@sparrow-library/src/forms/search/Search.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
Labels: pr-bugfix

#2867 updates in left panel
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: pr-bugfix

#2871 fix: made collection and environmemnt page temporary []
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
Labels: pr-bugfix

#2873 fix: handle catch block for handling api response
  apps/@sparrow-web/src/containers/api/api.common.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-common/src/utils/status-code.ts
Labels: bug

#2874 Rollback: rolling backing the changes for auto environment select
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: pr-bugfix

#2875 fix: removing main tab only if it exists
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
Labels: pr-bugfix

#2878 fix: Truncating the tab names if too long
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: pr-bugfix
