Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-10, with the labels that each got.

#3859 feat: test flow schedule run view SPRW-2129.
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.svelte
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.svelte
  packages/@sparrow-common/src/factory/init-tab.ts
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-common/src/types/workspace/testflow-schedule-run-view-tab.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-common/src/utils/init-testflow-schedule-run-view-tab.ts
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/TestResults.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/index.ts
  packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/layout/TestflowScheduleRVExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/layout/index.ts
Labels: pr-feature

#3868 Added schedule row component [SPRW-2084]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-library/src/icons/ErrorWithText.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/schedule-row/ScheduleRow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: feature

#3870 Merge development into main
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/package.json
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
Labels: documentation, maintainer, enhancement

#3863 Add schedule run functionality in the configuration page.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.svelte
  packages/@sparrow-common/src/components/email-receipents-picker/EmailReceipentsPicker.svelte
  packages/@sparrow-common/src/components/email-receipents-picker/types/email-receipents.ts
  packages/@sparrow-common/src/components/email-receipents-picker/types/index.ts
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/component/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/layout/ScheduleRunPopUp.svelte
  packages/@sparrow-common/src/features/schedule-run-pop-up/types/index.ts
  packages/@sparrow-common/src/types/workspace/testflow-dto.ts
  packages/@sparrow-common/src/types/workspace/testflow-schedule-tab.ts
  packages/@sparrow-common/src/utils/init-testflow-schedule-tab.ts
  packages/@sparrow-library/src/forms/date-picker/DatePicker.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/schedule-row/ScheduleRow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/TestResults.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/sub-components/Result.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
Labels: feature

#3878 Add schedule run functionality.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/schedule-row/ScheduleRow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte
  packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
Labels: feature

#3894 fix: test flow response formatting issue.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3905 fix: post hog events properties issue SPRW-2149.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3832 fix: hub UI issues SPRW-1937.
  packages/@sparrow-library/src/forms/label-field/LabelField.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-bugfix
