Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-06, with the labels that each got.

#3261 fix: AI request fixes [SPRW-1187]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  packages/@sparrow-common/src/types/workspace/ai-request-base.ts
  packages/@sparrow-common/src/types/workspace/ai-request-dto.ts
  packages/@sparrow-common/src/utils/init-ai-request-tab.ts
  packages/@sparrow-library/src/icons/GoogleVectorIcon.svelte
  packages/@sparrow-library/src/ui/toggle/Toggle.svelte
  packages/@sparrow-workspaces/package.json
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-config-selection/AiConfigurations.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-options/ModelOptions.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/constants/AiModelConfigurations.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/constants/index.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
Labels: pr-bugfix

#3268 change s3 bucket
  .github/workflows/sparrow-plans.yml
Labels: bug, documentation, maintainer, enhancement

#3275 fix: disabled the marketplace in sparrow edge []
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
Labels: pr-bugfix

#3276 Sprw 1206 community plan as a user i should not be able to make selective runs in test flows blocks
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/plan.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/plan.repository.ts
  apps/@sparrow-desktop/src/services/plan.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/plan.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/plan.repository.ts
  apps/@sparrow-web/src/services/plan.service.ts
Labels: pr-feature

#3280 fix: add gap between profile icon and right boundary [SPRW-986]
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: pr-bugfix

#3287 fix: update styling of My Activity as per figma [SPRW-1029]
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.svelte
  packages/@sparrow-library/src/icons/ChatMultipleRegular.svelte
  packages/@sparrow-library/src/icons/CommentRegular.svelte
  packages/@sparrow-library/src/icons/Sort.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
  packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte
Labels: pr-bugfix

#3282 fix: AI request fixes [SPRW-1216]
  packages/@sparrow-common/src/utils/init-ai-request-tab.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-config-selection/AiConfigurations.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/constants/AiModelConfigurations.ts
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
Labels: pr-bugfix

#3297 Add mock response integration.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/enums/item-type.enum.ts
  packages/@sparrow-common/src/types/workspace/http-response-mock-dto.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/no-mock-response-details-section/NoMockResponseDetailsSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3296 fix: update style of updates tab [SPRW-1027]
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.svelte
  packages/@sparrow-library/src/icons/FilterRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
  packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
  packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte
Labels: pr-style

#3293 Fix: Sparrow Plan bugs related to message name and invalid name SPRW-1225.
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-bugfix

#3301 Render the data in the list [SPRW-1150].
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3292 fix: multiple graphql issues
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
Labels: pr-bugfix

#3304 feat: added state property in mock response [SPRW-1230]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  packages/@sparrow-common/src/types/workspace/http-request-mock-tab.ts
Labels: pr-feature

#3302 put the functionality to update the mockresponse details on individua…
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3308 feat: updated functions to update local tab data of mock response [SPRW-1230]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: pr-feature

#3310 feat: added rename support for mock response [SPRW-1149]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
Labels: pr-feature

#3303 Add the functionality of deleting the mock responses [SPRW-1150].
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3311 Add the function to update the headers in mock response [SPRW-1233]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-headers/ResponseHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3306 feat: version history implementation [SPRW-848]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/ai-request-conversations.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/ai-request.repository.ts
  apps/@sparrow-desktop/src/services/ai-request.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/ai-request-conversations.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-web/src/repositories/ai-request.repository.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/ai-request.service.ts
  packages/@sparrow-common/src/types/workspace/ai-request-tab.ts
  packages/@sparrow-common/src/utils/init-ai-request-tab.ts
  packages/@sparrow-library/src/icons/EditRegular.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/chat-conversations/ConversationHistoryItem.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-options/ModelOptions.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-selector/ModelSectionInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
Labels: pr-feature

#3315 Add the functionality of active and inactive state of mock response [SPRW-1231].
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3307 feat: sparrow plans redirecting modal SPRW-1248.
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/plan.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/services/team.service.ts
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/plan.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/services/team.service.ts
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/plan-upgrade-modal/PlanUpgradeModal.svelte
  packages/@sparrow-common/src/enums/index.ts
  packages/@sparrow-common/src/enums/response.enum.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-common/src/utils/planUpgradeContent.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3272 feat: add environment from testflow
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/RequestAuthTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: bug

#3324 fix: fixed toggle issue for mock response [SPRW-1149]
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
Labels: pr-bugfix

#3078 build: add linux debian build support
  .github/workflows/sparrow-app-development.yml
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
  apps/@sparrow-desktop/src-tauri/assets/LinuxDeeplink.template
  apps/@sparrow-desktop/src-tauri/gen/schemas/linux-schema.json
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-desktop/src/components/App.svelte
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-common/src/components/default-header/DefaultHeader.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte
  packages/@sparrow-common/src/components/updater/Updater.svelte
  packages/@sparrow-common/src/enums/index.ts
  packages/@sparrow-common/src/enums/platform.enum.ts
  packages/@sparrow-common/src/features/app-updater/layout/AppUpdater.svelte
  packages/@sparrow-common/src/utils/OSDetector.ts
Labels: pr-feature, documentation, maintainer, enhancement

#3322 feat: added sparrow plans modal SPRW-1283.
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  packages/@sparrow-common/src/components/plan-upgrade-modal/PlanUpgradeModal.svelte
  packages/@sparrow-common/src/utils/planUpgradeContent.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-feature, pr-refactor

#3327 feat: add needs in workflow & rm unwanted env
  .github/workflows/sparrow-app-development.yml
Labels: bug, documentation, maintainer, enhancement

#3332 fix: add status code for changes comparison [SPRW-1232]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
Labels: pr-bugfix

#3333 fix: add conditional mapping for windows os
  apps/@sparrow-desktop/src-tauri/src/main.rs
Labels: pr-bugfix

#3331 feat: sparrow plans run history support.
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/plan.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/plan.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3294 Feat:Ai Rate Limiting [SPRW-1059]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-common/src/dto/ai-assistant.ts
Labels: feature

#3337 feat: made mock base url static [SPRW-1250]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
  packages/@sparrow-workspaces/src/utils/index.ts
  packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts
Labels: pr-feature

#3338 fix: fixed the mock request url []
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: pr-bugfix

#3321 feat: implemented generate prompt functionality [SPRW-1053]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-desktop/src/services/ai-assistant.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-web/src/services/ai-assistant.service.ts
  packages/@sparrow-common/src/dto/ai-assistant.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/generate-prompt/GeneratePrompt.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
Labels: pr-feature

#3329 Feat: Added Upgrade Banner [SPRW-1278]
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/constants/constants.ts
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/upgrade-plan-pop-up/UpgradePlanPopUp.svelte
  packages/@sparrow-common/src/components/upgrade-plan/UpgradePlanBanner.svelte
  packages/@sparrow-library/src/ui/tags/PlanTag.svelte
  packages/@sparrow-library/src/ui/tags/index.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
Labels: bug, documentation, maintainer, enhancement

#3340 fix: updated the admin panel direct link for payment.
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
Labels: pr-refactor

#3344 feat: add env VITE_SPARROW_AI_WEBSOCKET_PLANS
  .github/workflows/sparrow-plans.yml
Labels: bug, documentation, maintainer, enhancement

#3345 Resolve the mock response bugs.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts
  packages/@sparrow-workspaces/src/utils/tabular-input-theme.ts
Labels: bug

#3235 feat:add admin redirect in the dashboard profile
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/sub-component/UserProfileModal.svelte
  packages/@sparrow-library/src/icons/AdminLoginLogo.svelte
  packages/@sparrow-library/src/icons/index.ts
Labels: feature, pr-feature

#3346 fix: sparrow plans UI issues SPRW-1294.
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-common/src/utils/planUpgradeContent.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-bugfix

#3349 fix: disabled AI debug button for guest users & UI fix [SPRW-1303]
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3353 fix: sparrow edge issue for pop up.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3356 fix: removed base url in tab creation []
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3378 feat: upgraded sparrow version to v2.26.0 []
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: pr-version-upgrade

#3380 fix: added fixed name for sparrow
  .github/workflows/sparrow-app-development.yml
Labels: pr-build, documentation, maintainer, enhancement

#3370 Add the functionality of response ratio
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/number-input/NumberInput.svelte
  packages/@sparrow-common/src/types/workspace/http-response-mock-dto.ts
  packages/@sparrow-library/src/forms/index.ts
  packages/@sparrow-library/src/icons/DocumentPercentRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/index.ts
  packages/@sparrow-library/src/ui/progress-bar/ProgressBar.svelte
  packages/@sparrow-library/src/ui/progress-bar/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-response-state/MockResponseState.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-responses-ratio/MockResponsesRatio.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: feature

#3386 PR from mock-response-ratio to development [SPRW-1365].
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/number-input/NumberInput.svelte
  packages/@sparrow-common/src/types/workspace/http-response-mock-base.ts
  packages/@sparrow-common/src/types/workspace/http-response-mock-dto.ts
  packages/@sparrow-library/src/forms/index.ts
  packages/@sparrow-library/src/icons/DocumentPercentRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/index.ts
  packages/@sparrow-library/src/ui/progress-bar/ProgressBar.svelte
  packages/@sparrow-library/src/ui/progress-bar/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-response-state/MockResponseState.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-responses-ratio/MockResponsesRatio.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: bug, feature, documentation, maintainer, enhancement

#3366 fix: limit reach pop-up for a member UI issue SPRW-1339.
  packages/@sparrow-common/src/components/plan-upgrade-modal/PlanUpgradeModal.svelte
Labels: pr-bugfix

#3350 Fix the opening of collection [SPRW-1241].
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
Labels: bug

#3391 feat: implement global environment override issue [SPRW-1393]
  packages/@sparrow-workspaces/src/components/review-environment/ReviewEnvironment.svelte
Labels: bug

#3364 fix: global search support for sparrow edge for request, folder and environment. SPRW-1334.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3264 Fix: placeholder position of multiple lines SPRW-1073
  packages/@sparrow-library/src/forms/editor/theme.ts
Labels: bug

#3398 Fix the ratios bug.
  packages/@sparrow-common/src/components/number-input/NumberInput.svelte
Labels: bug

#3397 feat: tool tip animation support SPRW-1348.
  packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte
Labels: pr-feature

#3401 Fix the opening of collection tab when click of arrow button.
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
Labels: bug

#3403 feat: Animation side nav transition page
  apps/@sparrow-desktop/src/constants/animation.ts
  apps/@sparrow-desktop/src/pages/marketplace-page/MarketplacePage.svelte
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/constants/animation.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  apps/@sparrow-web/src/pages/marketplace-page/MarketplacePage.svelte
  packages/@sparrow-common/src/components/github-star-redirect/GithubStarRedirect.svelte
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/lanuch-desktop/LanuchDesktop.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-style

#3365 build: add support for mac app store build
  .github/workflows/sparrow-app-development.yml
  apps/@sparrow-desktop/src-tauri/Entitlements.plist
  apps/@sparrow-desktop/src-tauri/Info.plist
  apps/@sparrow-desktop/src-tauri/assets/Sparrow_Desktop.provisionprofile
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
Labels: bug, pr-build, documentation, maintainer, enhancement

#3408 build: add support for mac app store build
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-prod.yaml
Labels: bug, pr-build, documentation, maintainer, enhancement

#3412 fix: sidebar glitch issue SPRW-1389.
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
Labels: pr-bugfix

#3415 fix: mac dev build
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-prod.yaml
  .github/workflows/sparrow-app-test-pipeline.yml
Labels: bug, pr-refactor, pr-build, documentation, maintainer, enhancement
