Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-02, with the labels that each got.

#2559 APP/Webapp- UI issue in rest api section #2553
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
Labels: bug

#2569 feat: added global search in edge and fixed released issues []
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  packages/@sparrow-common/src/components/global-search/GlobalSearch.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/RecentItems.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/SearchBar.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/SearchSuggestions.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/SuggestionTags.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/types/types.ts
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-library/src/styles/style.scss
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: bug, feature

#2572 fix: fixed the reported bugs []
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/components/global-search/sub-components/NoResults.svelte
  packages/@sparrow-common/src/components/global-search/sub-components/RecentItems.svelte
  packages/@sparrow-library/src/icons/CheckCircle.svelte
Labels: bug

#2579 feat: added fluent icons in sparrow app and web app []
  apps/@sparrow-desktop/src/main.ts
  apps/@sparrow-web/src/main.ts
  packages/@sparrow-library/package.json
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Resizable.css
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Resizable.ttf
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Resizable.woff
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Resizable.woff2
Labels: feature

#2584 feat: updated the Modal Component []
  packages/@sparrow-library/src/ui/modal/Modal.svelte
Labels: story

#2588 Feat/ds button
  packages/@sparrow-common/src/components/LoginSingupConfirmation/LoginSignupConfirmation.svelte
  packages/@sparrow-common/src/components/popup/login-popup.svelte
  packages/@sparrow-common/src/components/switch-workspace/SwitchWorkspace.svelte
  packages/@sparrow-common/src/features/app-updater/layout/AppUpdater.svelte
  packages/@sparrow-common/src/features/create-team/components/team-actions/TeamActions.svelte
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-library/src/ui/button/Button.svelte
  packages/@sparrow-support/src/features/add-feedback/layout/AddFeedback.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackPost.svelte
  packages/@sparrow-teams/src/features/create-workspace/components/workspace-actions/WorkspaceActions.svelte
  packages/@sparrow-teams/src/features/leave-team/layout/LeaveTeam.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-teams/src/features/workspace-members/components/header/Header.svelte
  packages/@sparrow-teams/src/features/workspace-members/components/member/Member.svelte
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/welcome-popup/layout/WelcomePopup.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte
  packages/@sparrow-workspaces/src/hoc/WithModal.svelte
Labels: design

#2596 fix: fixed cross icon casing []
  packages/@sparrow-library/src/icons/index.ts
Labels: bug

#2604 fix: collection list open issue []
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#2606 [Teams & Workspace] UI glitch while creating workspace
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#2607 fix: fixed the open collection issue []
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: bug

#2608 Feat/storybook ds tabs updates
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/workspace-members/layout/WorkspaceMembers.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-navigator/RequestNavigatorTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-navigator/ResponseNavigator.svelte
Labels: design

#2612 fix: fixed ui issues []
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte
Labels: bug

#2613 Feat/storybook ds page navigation
  packages/@sparrow-library/src/assets/EmptyCollectionIcon.svg
  packages/@sparrow-library/src/assets/GraphQL.svg
  packages/@sparrow-library/src/assets/SocketIoIcon.svg
  packages/@sparrow-library/src/assets/folderIcon3.svg
  packages/@sparrow-library/src/assets/index.ts
  packages/@sparrow-library/src/icons/FolderIcon.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: design

#2615 fix: fixed color issues []
  packages/@sparrow-library/src/forms/search/Search.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
Labels: bug

#2617 fix: shortcut bug and toggle bug
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
Labels: bug

#2618 Feat/storybook ds checkbox
  packages/@sparrow-library/src/forms/checkbox/Checkbox.svelte
  packages/@sparrow-library/src/forms/index.ts
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
Labels: design

#2634 bug in ds-tabs graphQL
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
Labels: bug

#2645 fix: global search import []
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
Labels: bug

#2650 Filter chips
  packages/@sparrow-common/src/features/global-search/components/SuggestionTags/SuggestionTags.svelte
  packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
  packages/@sparrow-library/src/icons/ArrowSwapRegular.svelte
  packages/@sparrow-library/src/icons/FlowChartRegular.svelte
  packages/@sparrow-library/src/icons/FolderRegular.svelte
  packages/@sparrow-library/src/icons/LayerRegular.svelte
  packages/@sparrow-library/src/icons/StackRegular.svelte
  packages/@sparrow-library/src/icons/WorkspaceRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/chip/FilterChip.svelte
  packages/@sparrow-library/src/ui/chip/index.ts
Labels: design

#2651 Filter chips
  packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
  packages/@sparrow-library/src/ui/chip/FilterChip.svelte
Labels: design

#2660 Teams left panel
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-library/src/icons/ChevronDoubleLeftRegular.svelte
  packages/@sparrow-library/src/icons/ChevronDoubleRightRegular.svelte
  packages/@sparrow-library/src/icons/CommunityFilled.svelte
  packages/@sparrow-library/src/icons/CommunityRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/components/api-list-items/ApiListItem.svelte
  packages/@sparrow-teams/src/features/recent-apis/layout/RecentApi.svelte
  packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: design

#2664 fix: Focused state circle issue of radio button.
  packages/@sparrow-library/src/ui/radio-button/RadioButton.svelte
Labels: bug

#2663 fix: for new users fixed tour guide ai winodw rest tab creation [#104]
  apps/@sparrow-web/src/components/App.ts
Labels: bug

#2661 feat: Added temporary tabs functionality [SPRW-46]
  apps/@sparrow-desktop/src/adapter/request-tab.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/tab.repository.ts
  apps/@sparrow-web/src/adapter/request-tab.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/tab.repository.ts
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-common/src/utils/init-collection-tab.ts
  packages/@sparrow-common/src/utils/init-environment-tab.ts
  packages/@sparrow-common/src/utils/init-folder-tab.ts
  packages/@sparrow-common/src/utils/init-graphql-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-common/src/utils/init-socket-io-tab.ts
  packages/@sparrow-common/src/utils/init-testflow-tab.ts
  packages/@sparrow-common/src/utils/init-web-socket-tab.ts
  packages/@sparrow-common/src/utils/init-workspace-tab.ts
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: front end, feature

#2665 feat: global search feedbacks addresses [SPRW-97]
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-library/src/forms/editor/Editor.svelte
Labels: bug, task

#2671 feat: Test flow cards revamp
  packages/@sparrow-library/src/icons/CheckmarkCircleRegular.svelte
  packages/@sparrow-library/src/icons/ChevronLeftFilled.svelte
  packages/@sparrow-library/src/icons/ClockRegular.svelte
  packages/@sparrow-library/src/icons/ErrorCircleRegular.svelte
  packages/@sparrow-library/src/icons/InfoRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: feature

#2675 fix: preview test flow card Icon position.
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
Labels: bug

#2678 fix: disable all the saved response properties
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/form-data/FormData.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-parameters/RequestParameters.svelte
Labels: story

#2674 bug: Left Workspace Panel . Add gap between patch and it's text .
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: bug
