Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-09, with the labels that each got.

#3694 feat: generate variable tour guide SPRW-1815.
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-desktop/src/services/user.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  apps/@sparrow-web/src/services/user.service.ts
  packages/@sparrow-common/src/types/workspace/http-request-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte
  packages/@sparrow-workspaces/src/components/generate-variable-environment/generateVariableEnvironment.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/generate-variables-tour-guide/components/GenerateVariableGuideCard.svelte
  packages/@sparrow-workspaces/src/features/generate-variables-tour-guide/components/TourguideOverlay.svelte
  packages/@sparrow-workspaces/src/features/generate-variables-tour-guide/layout/GenerateVariableTourGuide.svelte
  packages/@sparrow-workspaces/src/features/generate-variables-tour-guide/utils/generateVariableTourContent.ts
  packages/@sparrow-workspaces/src/features/generate-variables-tour-guide/utils/index.ts
  packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/assets/images/Sparkle.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/assets/images/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/components/generate-variable-card/GenerateVariableCard.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/stores/generate-variable-demo.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: pr-feature

#3677 fix:Sprw 1802 alignment issues observed in url use variables
  packages/@sparrow-workspaces/src/features/collection-list/components/ai-request/AiRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
Labels: bug

#3699 fix:SPRW-1827 Prevent Pixel Flood Attack via Image Uploads
  packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
  packages/@sparrow-common/src/features/create-team/constants/icon.ts
  packages/@sparrow-common/src/features/create-team/types/form.ts
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
  packages/@sparrow-teams/src/features/team-settings/types/team-profile.ts
Labels: bug

#3651 fix: global search folder issue SPRW-1754.
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
Labels: pr-bugfix

#3703 fix: AI chat bot interface rendering issue SPRW-1302.
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
Labels: pr-bugfix

#3721 fix: negative time issue
  packages/@sparrow-common/src/utils/formatTime.ts
  packages/@sparrow-support/src/components/CommentCard.svelte
Labels: bug

#3741 feat: added response test result UI section [SPRW-1858]
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-test-results/ResponseTestResults.svelte
Labels: bug, pr-bugfix

#3726 fix: generate mock data issue while update.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3750 feat: added new badge type for test results [SPRW-1858]
  packages/@sparrow-library/src/ui/badge/Badge.svelte
  packages/@sparrow-library/src/ui/navigator/Navigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-feature

#3749 feat: assertion no code tour guide SPRW-1851.
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/user.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/user.service.ts
  packages/@sparrow-common/src/types/workspace/http-request-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/components/TourGuideCard.svelte
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/components/index.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/index.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/layout/RequestNoCodeTourGuide.svelte
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/layout/index.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/utils/index.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/utils/requestTabCardfunctions.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/utils/requestTabNocodeCardPosition.ts
  packages/@sparrow-workspaces/src/features/request-no-code-tour-guide/utils/requestTabTestsTourContent.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tour-guide-card/RequestTourGuideCard.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/stores/index.ts
  packages/@sparrow-workspaces/src/stores/request-tab-test-tour-guide.ts
Labels: pr-feature

#3751 fix: sparrow edge mock data is invisible.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3762 feat: assertion setup for script SPRW-1924.
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/utils/common-snippets.ts
Labels: pr-feature

#3763 fix: mock data issue (temporary fix)
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/RequestBody.svelte
Labels: bug

#3786 feat: assertion snippets with JavaScript editor syntax error support. SPRW-1925
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/utils/common-snippets.ts
Labels: pr-feature

#3746 fix: text editor lag
  packages/@sparrow-library/src/forms/text-editor/TextEditor.svelte
Labels: pr-bugfix, enhancement

#3795 fix: assertion script LHS panel search update SPRW-1924.
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
Labels: pr-bugfix

#3720 fix: generate variable edge case issues SPRW-1897.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
Labels: pr-bugfix

#3785 fix: mock data restrictions during bulk edit of headers and params SPRW-2022.
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3800 fix: windows build pipeline
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-prod.yaml
Labels: pr-bugfix, pr-build, maintainer

#3804 fix: AI chat data missing issue SPRW-2027.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
Labels: pr-bugfix

#3810 fix: assertion tour guide for desktop issue SPRW-1921.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/request-tab-tour-guide/utils/requestTabScriptCardPositions.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3812 Fix/generate ai test bug.
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: bug

#3803 Feat: Switch case implemented [SPRW-1930]
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: feature

#3743 Fix: list Navigation-button-fix [SPRW-1076]
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: bug

#3827 Fix UI bugs.
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
Labels: bug

#3825 fix: validation check for hub name SPRW-1910.
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
Labels: pr-bugfix

#3845 Add schedule run functionality.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/services/testflow.service.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-common/src/features/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/component/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/component/invite-user-pickers/InviteUserPicker.svelte
  packages/@sparrow-common/src/features/schedule-run-pop-up/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/layout/ScheduleRunPopUp.svelte
  packages/@sparrow-common/src/features/schedule-run-pop-up/types/index.ts
  packages/@sparrow-common/src/features/schedule-run-pop-up/types/invite-picker.ts
  packages/@sparrow-library/src/forms/date-picker/DatePicker.svelte
  packages/@sparrow-library/src/forms/index.ts
  packages/@sparrow-library/src/forms/time-picker/TimePicker.svelte
  packages/@sparrow-library/src/icons/ArrowLeftRegularIcon.svelte
  packages/@sparrow-library/src/icons/CalendarRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/index.ts
  packages/@sparrow-library/src/ui/step-progress-bar/StepProgressBar.svelte
  packages/@sparrow-library/src/ui/step-progress-bar/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: feature

#3853 Revert "bug: Fix snippets vertical text alignment[1924]"
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
Labels: maintainer

#3855 Feat: Run management [SPRW-2084] [SPRW-2082] [SPRW-2086]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-library/src/icons/ClockIcon.svelte
  packages/@sparrow-library/src/icons/Dropdown.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/icons/warningIcon.svelte
  packages/@sparrow-library/src/ui/index.ts
  packages/@sparrow-library/src/ui/pagination/Pagination.svelte
  packages/@sparrow-library/src/ui/pagination/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/save-testflow/SaveTestflow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: feature
