Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-08, with the labels that each got.

#3550 Fix: folder creation tab issue SPRW-1083.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: pr-bugfix

#3555 fix: Workspace members background issue SPRW-703.
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/images/Sparrowbirdoutline.png
  packages/@sparrow-workspaces/src/features/workspace-explorer/images/index.ts
Labels: pr-bugfix

#3561 fix: trial plan button position issue SPRW-705.
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
Labels: pr-bugfix

#3566 fix:Tooltip overlapping is observed in rest API and test flow section
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: bug, pr-bugfix

#3568 fix: folder issue from default collection dropdown SPRW-634.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3588 Revert "fix: Replaced the upgrade logic of sparrow websocket to inbuild crate"
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
  apps/@sparrow-desktop/src-tauri/src/main.rs
  packages/@sparrow-common/src/utils/init-web-socket-tab.ts
Labels: maintainer

#3591 remove sync version
  .github/workflows/sparrow-app-marketplace.yml
  .github/workflows/sparrow-app-prod.yaml
  .husky/pre-commit
  package.json
Labels: documentation, maintainer, enhancement

#3597 Development
  package.json
Labels: bug, documentation, maintainer, enhancement

#3600 patch: Development to main
  CHANGELOG.md
  package.json
Labels: bug, documentation, maintainer, enhancement

#3584 fix: update admin redirect url
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-bugfix

#3602 fix: update docs path
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-web/src/constants/constants.ts
Labels: pr-bugfix

#3610 feat: Generate variables UI and functionality setup SPRW-1735.
  apps/@sparrow-desktop/src/models/environment-tab.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  packages/@sparrow-common/src/utils/init-environment-tab.ts
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/components/GenerateVariablesLoading.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/components/SparkleRotating.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/index.ts
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle1.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle2.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle3.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle4.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle5.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/icons/sparkle6.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/index.ts
  packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte
Labels: feature

#3611 fix: generate variable Rxdb update.
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/environment-tab.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
Labels: pr-bugfix

#3617 fix: updated the codemirror-json5 packager version [SPRW-1706]
  package.json
  yarn.lock
Labels: bug, pr-bugfix

#3620 fix: generate variable conditions.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte
Labels: pr-bugfix

#3630 feat: generate variable restrictions along with undo for generate variables SPRW-1762.
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-feature

#3637 fix: generate button issue.
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-bugfix

#3640 fix: condition of generate variable button.
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-bugfix

#3657 fix: generate variable undo issue SPRW-1652.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
Labels: pr-bugfix

#3666 fix: generate variable UI bugs SPRW-1791.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/components/GenerateVariablesLoading.svelte
  packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte
Labels: pr-bugfix

#3688 fix:Collection name exceeds character limit but still gets accepted
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: bug

#3675 fix:Sprw 1509 animation glitch in rest api shortcut section
  packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
Labels: bug

#3648 fix: Multiple bugs in ticket no 439,635,1139
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-support/src/components/Attachment/Attachment.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#3689 fix:User is able to add extra variable in generate variable section and not able to remove it
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
Labels: bug

#3660 fix: removed help me debug from public workspace [SPRW-1787]
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: bug, pr-bugfix

#3647 fix: fixed request text issue in AI Request saved operation [SPRW-1730]
  packages/@sparrow-common/src/types/workspace/ai-request-base.ts
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: bug, pr-bugfix

#3692 feat: add mac(Intel) build to pipeline
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-prod.yaml
  .github/workflows/sparrow-app-test-pipeline.yml
  package.json
Labels: bug, documentation, maintainer, enhancement

#3653 fix: json formatting
  packages/@sparrow-library/src/forms/editor/editor.ts
Labels: pr-bugfix

#3671 fix: app relaunch after auto-update on windows
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-marketplace.yml
  .github/workflows/sparrow-app-prod.yaml
  .husky/pre-commit
  CHANGELOG.md
  scripts/sync-version.js
Labels: bug, documentation, maintainer, enhancement
