Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-05, with the labels that each got.

#3053 fix: Fixed UI for public workspace and hubs [SPRW-850]
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
  packages/@sparrow-library/src/icons/LinkRegular.svelte
  packages/@sparrow-library/src/icons/StatusSuccess.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/components/table/subcomponents/Rows.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-bugfix

#3014 Add sentry integration for app .
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/main.ts
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-desktop/src/utils/jwt.ts
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/main.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/utils/jwt.ts
  package.json
  packages/@sparrow-common/src/features/app-updater/layout/AppUpdater.svelte
  packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
  packages/@sparrow-common/src/utils/common.helper.ts
  packages/@sparrow-common/src/utils/handle-downlod-rest.ts
  packages/@sparrow-common/src/utils/importCollectionValidations.ts
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview/ResponsePreview.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  yarn.lock
Labels: feature

#3055 feat: added hub url details [SPRW-850]
  apps/@sparrow-desktop/src/adapter/team.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/team.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/team.repository.ts
  apps/@sparrow-web/src/adapter/team.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/team.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/repositories/team.repository.ts
  packages/@sparrow-common/src/interfaces/team.interface.ts
  packages/@sparrow-common/src/types/teams/team-dto.ts
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-library/src/icons/LinkdinIcon.svelte
  packages/@sparrow-library/src/icons/XIcon.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-teams/src/features/team-settings/components/index.ts
  packages/@sparrow-teams/src/features/team-settings/components/team-links/TeamLinks.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/TeamsProfile.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
  packages/@sparrow-teams/src/features/team-settings/layout/TeamSettings.svelte
Labels: pr-feature

#3049 feat: Dynamic expression model improvements.
  packages/@sparrow-library/src/assets/MathFormulaFunction.svg
  packages/@sparrow-library/src/assets/index.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3057 Implement dynamic expression to the testflow
  .github/workflows/sparrow-app-prod.yaml
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/package.json
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/types/workspace/testflow-tab.ts
  packages/@sparrow-library/package.json
  packages/@sparrow-library/src/assets/MathFormulaFunction.svg
  packages/@sparrow-library/src/assets/index.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
  packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElementFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/index.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/functionOptionsData.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/RequestAuthTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/form-data/FormData.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/store/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/store/testflow.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/decode-testflow.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/reduce-auth-header.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/reduce-auth-parameter.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/reduce-query-params.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/reduce-request-url.ts
Labels: bug, documentation, maintainer, enhancement

#3060 Fix: dynamic expression model issues.
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
Labels: pr-bugfix

#3063 fix: solved public workspace UI bugs [SPRW-895]
  packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/TeamsProfile.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
  packages/@sparrow-teams/src/features/team-settings/layout/TeamSettings.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
Labels: pr-bugfix

#3064 feat: fix dynamic expression drag and drop
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
Labels: bug

#3062 feat: enabling suggestions of normal user queries + code refactoring
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix, pr-feature

#3071 Revert "feat: enabling suggestions of normal user queries + code refactoring"
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: maintainer

#3073 fix: dynamic expression editor alignment.
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
Labels: pr-bugfix

#3091 Fix the usable sentry logs.
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/main.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/main.ts
Labels: feature

#3094 feat: upgrade version bump [#1]
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: enhancement

#3095 Revert "feat: upgrade version bump [#1]"
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: maintainer

#3042 feat: update docker-compose and add Nginx configuration for SSL and r…
  docker-compose.yml
  nginx/conf.d/sparrow.conf
Labels: bug, documentation, maintainer, enhancement

#3103 fix: fixed type in workspace []
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
Labels: pr-bugfix

#3102 fix: fixed the typo and disabled the deepseek option [SPRW-943, SPRW-944]
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
Labels: pr-bugfix

#3106 fix: add patch v2-23-1
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
Labels: enhancement

#3104 feat: Test flow Delete single block SPRW-877.
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3109 feat: Testflow connecting deleting Block SPRW-878
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3077 fix: testflow dynamic expression UI and functionality issues.
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElementFormData.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3080 feat: Testflow Enhancement for environment usage.
  packages/@sparrow-library/src/ui/alert/Alert.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: pr-feature

#3087 fix:added red border to graph ql and rest
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: pr-bugfix

#3079 Fix initial page rendering while navigating to workspace section SPRW-687.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: bug

#2984 fix: add spinner to handle loading delay on initial API call
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: pr-bugfix

#3084 fix the test flow name [SPRW-781]
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-name/TestFlowName.svelte
  packages/@sparrow-workspaces/src/utils/index.ts
  packages/@sparrow-workspaces/src/utils/test-flow-name-theme.ts
Labels: bug

#3112 feat: implement LHS panel area of mock collection [SPRW-924]
  packages/@sparrow-library/src/icons/MockCollection.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/components/card/Card.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-feature

#3114 Testflow phase 2
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-library/src/ui/alert/Alert.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElementFormData.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: documentation, maintainer, enhancement

#3115 fix: testflow deleting correction SPRW-896
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3122 feat: added mock collection type filter [SPRW-957]
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
Labels: pr-feature

#3100 Fix the ui bugs of public workspaces [SPRW-902].
  packages/@sparrow-common/src/features/create-team/constants/description.ts
  packages/@sparrow-common/src/features/create-team/constants/icon.ts
  packages/@sparrow-common/src/features/create-team/constants/name.ts
  packages/@sparrow-library/src/forms/Input/Input.svelte
  packages/@sparrow-library/src/forms/label-field/LabelField.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-links/TeamLinks.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
Labels: bug

#3105 Fix the UI bugs of public workspace [SPRW-911]
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
Labels: bug

#3123 feat: add mock sever LHS panel [SPRW-925]
  packages/@sparrow-library/src/icons/DatabaseStackRegular.svelte
  packages/@sparrow-library/src/icons/HistoryRegular.svelte
  packages/@sparrow-library/src/icons/PlayCircleRegular.svelte
  packages/@sparrow-library/src/icons/RecordStopRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-feature

#3130 Remove the sentry logs for handled errors [SPRW-1006]
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
  packages/@sparrow-common/src/utils/common.helper.ts
  packages/@sparrow-common/src/utils/handle-downlod-rest.ts
  packages/@sparrow-common/src/utils/importCollectionValidations.ts
  packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview/ResponsePreview.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: feature

#3118 feat: deepseek model support and disabling other model for now [SPRW-667]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-common/src/types/workspace/http-request-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3124 Fix ui and functional bugs of workspaces [SPRW-981].
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: bug

#3132 feat: implement delete mock collection [SPRW-959]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-feature

#3133 Mock server
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/main.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/main.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-common/src/dto/collection.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-library/package.json
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Regular.css
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Regular.ttf
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Regular.woff
  packages/@sparrow-library/src/fluent-icons/FluentSystemIcons-Regular.woff2
  packages/@sparrow-library/src/icons/DatabaseStackRegular.svelte
  packages/@sparrow-library/src/icons/HistoryRegular.svelte
  packages/@sparrow-library/src/icons/PlayCircleRegular.svelte
  packages/@sparrow-library/src/icons/RecordStopRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/components/card/Card.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-feature, documentation, maintainer, enhancement

#3134 Sprw 966 test flows reconnecting adding or rewiring of the block
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/icons/AddCircleRegular.svelte
  packages/@sparrow-library/src/icons/DismissCircleFilled.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3135 fix: mock collection folder and rename [SPRW-958]
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
Labels: pr-feature

#3137 fix: fixed app crash on register []
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
Labels: pr-bugfix

#3139 SPRW-983 feat: implement testflow blocks rewiring
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3140 Fix: dynamic expression condition model correction.
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3136 feat: test flow tour guide SPRW-678
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte
  packages/@sparrow-workspaces/src/components/test-flow-tour-guide/TestFlowTourGuide.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/utils/sample-request.ts
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-feature

#3116 fix: Left panel test flow scroll issue SPRW-969.
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: pr-bugfix

#2956 fix: autofocus text area in response body
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-schema/RequestSchema.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-variables/RequestVariables.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/raw/Raw.svelte
Labels: pr-bugfix

#3145 Feat: add folder explorer for mock collection
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: pr-feature

#3143 feat: implement testflow redirect link
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
Labels: pr-doc

#3148 fix: testflow UI alignment bugs
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3147 Fix: test flow tour guide UI issue SPRW-678
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-bugfix

#3150 feat: implement dynamic expression dependency check
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#3152 feat: added mock request creation in folder and mock running status [SPRW-1008]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-feature

#3127 Fix: test flow environment miss alert size issue SPRW-761
  packages/@sparrow-library/src/ui/alert/Alert.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: pr-bugfix

#3154 feat: mock rest api, tab type and status code [SPRW-1009]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/mock-request/MockRequest.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/index.ts
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: pr-feature

#3155 fix/workspace-invite-bugs.
  packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte
  packages/@sparrow-common/src/features/create-team/constants/icon.ts
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
Labels: bug

#3157 Fix: make select component searchable
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: pr-bugfix

#3156 feat: added functionality to save response code []
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: pr-feature

#3160 Feat/implement testflow fixes
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: bug

#3158 Fix: Dynamic Expression Functions Options of JSON SPRW-928
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/functionOptionsData.ts
Labels: enhancement

#3162 fix: Mock REST API toast notification
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
Labels: pr-bugfix

#3164 fix: fixed mock rest api not creating from collection explorer page [SPRW-1056]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-bugfix

#3161 Fix: mock restapi url space
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/utils/index.ts
  packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts
Labels: pr-bugfix

#3121 Feat: Group policy Support
  CHANGELOG.md
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
  apps/@sparrow-desktop/src-tauri/assets/AIRegistry.wxs
  apps/@sparrow-desktop/src-tauri/assets/AdmxAdmlSupport/AdmxAdmlCreator.py
  apps/@sparrow-desktop/src-tauri/assets/AdmxAdmlSupport/en-US/sparrow.adml
  apps/@sparrow-desktop/src-tauri/assets/AdmxAdmlSupport/sparrow.admx
  apps/@sparrow-desktop/src-tauri/assets/LoginRegistry.wxs
  apps/@sparrow-desktop/src-tauri/assets/WorkspaceRegistry.wxs
  apps/@sparrow-desktop/src-tauri/src/group_policy_config.rs
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/components/banner/login-banner.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/store/index.ts
  packages/@sparrow-common/src/store/policyStore.ts
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  yarn.lock
Labels: feature

#3168 fix: mock rest api count
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
Labels: pr-bugfix

#3169 fix: fixed mock server bugs [SPRW-1056]
  packages/@sparrow-workspaces/src/features/collection-list/components/mock-request/MockRequest.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
Labels: pr-bugfix

#3172 fix: chatbot code font style [SPRW-942]
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
Labels: pr-bugfix

#3173 Fix overflow hidden property for the modal component [SPRW-1065].
  packages/@sparrow-common/src/features/published-workspace/layout/PublishedWorkspace.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
Labels: bug

#3174 fix: fixed the hubs heading [SPRW-693]
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
Labels: pr-bugfix

#3176 fix: profile icon spacing
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: pr-bugfix

#3180 Revert "fix: profile icon spacing"
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: maintainer

#3179 fix: add-redirects
  apps/@sparrow-web/src/components/App.ts
Labels: pr-feature

#3183 Revert "fix: add space in profile icon and right boundary [SPRW-986]"
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: maintainer

#3181 feat: enable editor copy text
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
Labels: bug

#3165 Viewer Flow Refinements [SPRW-963]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: feature

#3184 fix: sparrow release timeline url
  packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
Labels: pr-bugfix

#3163 feat: posthog Events for AI and test flow dynamic expression SPRW-967
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-common/src/utils/events.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-library/src/forms/editor/MergeView.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElementFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditorMergeView.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/functionOptionsData.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-tour-guide/layout/WorkspaceTourGuide.svelte
Labels: pr-feature

#3190 fix: editor cursor position breaking
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
Labels: pr-bugfix

#3187 fix: AI request tab fixes
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  packages/@sparrow-common/src/images/sparrow-logo.svelte
  packages/@sparrow-library/src/forms/editor/mergeViewUtil.ts
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/icons/BetaVectorIcon.svelte
  packages/@sparrow-library/src/icons/BotRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-options/ModelOptions.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-selector/ModelSectionInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-bugfix

#3191 fix: fixed condition comparison issue, updated dropdown for desktop
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-bugfix

#3197 feat: added history model and explorer page [SPRW-1030]
  apps/@sparrow-desktop/src/adapter/mock-history-tab.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  apps/@sparrow-web/src/adapter/mock-history-tab.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  packages/@sparrow-common/src/factory/init-tab.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/collection-dto.ts
  packages/@sparrow-common/src/types/workspace/http-request-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-mock-base.ts
  packages/@sparrow-common/src/types/workspace/mock-history-base.ts
  packages/@sparrow-common/src/types/workspace/mock-history-dto.ts
  packages/@sparrow-common/src/types/workspace/mock-history-method.ts
  packages/@sparrow-common/src/types/workspace/mock-history-tab.ts
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-common/src/utils/init-mock-history-tab.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/MockHistoryExplorer.svelte
Labels: pr-feature

#3198 fix: testflow operation UI
  packages/@sparrow-teams/src/features/invited-users/layout/InvitesView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte
Labels: pr-feature

#3201 feat: added paginated fetch public workspace flow [SPRW-1033]
  apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/workspace.repository.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte
Labels: pr-feature

#3200 feat: app version upgrade
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: documentation

#3205 feat: added view history and navigation [SPRW-1030]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-feature

#3209 fix: testflow renders from global search [SPRW-1141]
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/NoResults.svelte
Labels: bug

#3210 feat: implement mock request history page
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-library/src/forms/editor/theme.ts
  packages/@sparrow-library/src/icons/HistoryIcon.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/HistoryTable.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/sub-component/history-table-expanded/HistoryTableExpanded.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/MockHistoryExplorer.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/types/api-history.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/types/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: pr-feature

#3211 Move Mock server phase 2 to development
  apps/@sparrow-desktop/src/adapter/mock-history-tab.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/adapter/mock-history-tab.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-common/src/factory/init-tab.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/collection-dto.ts
  packages/@sparrow-common/src/types/workspace/http-request-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-mock-base.ts
  packages/@sparrow-common/src/types/workspace/mock-history-base.ts
  packages/@sparrow-common/src/types/workspace/mock-history-dto.ts
  packages/@sparrow-common/src/types/workspace/mock-history-method.ts
  packages/@sparrow-common/src/types/workspace/mock-history-tab.ts
  packages/@sparrow-common/src/types/workspace/tab.ts
  packages/@sparrow-common/src/utils/init-mock-history-tab.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-library/src/forms/editor/theme.ts
  packages/@sparrow-library/src/icons/HistoryIcon.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/HistoryTable.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/sub-component/history-table-expanded/HistoryTableExpanded.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/MockHistoryExplorer.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/index.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/types/api-history.ts
  packages/@sparrow-workspaces/src/features/mock-history-explorer/types/index.ts
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: pr-feature, documentation, maintainer, enhancement

#3216 fix: add notifications import [SPRW-1082]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
Labels: pr-bugfix

#3220 Fix the marketplace bugs .
  apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
  apps/@sparrow-web/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
  packages/@sparrow-common/src/components/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte
Labels: bug

#3225 fix: global search path for testflow and environment [SPRW-931]
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
Labels: bug

#3223 Fix the bugs in the workspace grid card.
  packages/@sparrow-common/src/components/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte
Labels: bug

#3227 fix: history table row expand behavior on click [SPRW-1094]
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/HistoryTable.svelte
Labels: pr-bugfix

#3224 Add the workspace details page [SPRW-1085].
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  packages/@sparrow-common/src/components/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-common/src/icons/SparrowOutlineIcon.svelte
  packages/@sparrow-common/src/icons/index.ts
  packages/@sparrow-library/src/icons/ShareMultipleRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-feature

#3226 feat: community plan test flow history SPRW-1048.
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/services/workspace.service.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3215 feat: Added chat auto clear toggler, clear chat and multi shot prompting [#SPRW-1054]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/types/workspace/ai-request-base.ts
  packages/@sparrow-common/src/types/workspace/ai-request-dto.ts
  packages/@sparrow-common/src/types/workspace/ai-request-tab.ts
  packages/@sparrow-common/src/utils/init-ai-request-tab.ts
  packages/@sparrow-library/src/icons/AnthropicVectorIcon.svelte
  packages/@sparrow-library/src/icons/DeepseekVectorIcon.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-config-selection/AiConfigurations.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-options/ModelOptions.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-auth/RequestAuth.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
Labels: pr-feature

#3239 Add the collection page for the shared workspaces.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: feature, enhancement

#3233 feat: AI request UI and functional fixes [SPRW-1158]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-common/src/types/workspace/ai-request-base.ts
  packages/@sparrow-common/src/types/workspace/ai-request-dto.ts
  packages/@sparrow-common/src/utils/init-ai-request-tab.ts
  packages/@sparrow-library/src/icons/BotSparkleRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-options/ModelOptions.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-selector/ModelSectionInput.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
  packages/@sparrow-workspaces/src/features/ai-request-explorer/store/ai-request-explorer.ts
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
Labels: pr-bugfix

#3234 feat: enabled AI debugging for 5xx status codes [SPRW-1020]
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-feature

#3231 feat: Plan restriction for UI and added model to support SPRW-1048.
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/plan.model.ts
  apps/@sparrow-desktop/src/models/team.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/plan.repository.ts
  apps/@sparrow-desktop/src/repositories/testflow.repository.ts
  apps/@sparrow-desktop/src/services/plan.service.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/plan.model.ts
  apps/@sparrow-web/src/models/team.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/repositories/plan.repository.ts
  apps/@sparrow-web/src/repositories/testflow.repository.ts
  apps/@sparrow-web/src/repositories/workspace.repository.ts
  apps/@sparrow-web/src/services/plan.service.ts
  apps/@sparrow-web/src/services/workspace.service.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#3229 feat: implement plan view space at hub level [SPRW-905]
  apps/@sparrow-desktop/src/adapter/team.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/team.model.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/team.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/team.repository.ts
  packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-feature

#3248 feat: integrated hub page with details [SPRW-1036]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/HubExplorerPage/HubExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/hub-explorer/index.ts
  packages/@sparrow-workspaces/src/features/hub-explorer/layout/HubExplorer.svelte
  packages/@sparrow-workspaces/src/features/hub-explorer/layout/index.ts
  packages/@sparrow-workspaces/src/features/index.ts
Labels: pr-feature

#3250 feat: completed the Switch dropdown [SPRW-1087]
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/recent-workspace.repository.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/recent-workspace.repository.ts
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/forms/select/menu-items/MenuItemsv2.svelte
Labels: pr-feature

#3252 fix: scrolling on recent public workspaces.
  packages/@sparrow-marketplace/src/features/recent-public-workspaces/layout/RecentPublicWorkspace.svelte
Labels: bug

#3188 Fix the public workspace modal text and alignment of checkbox.
  packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
Labels: bug

#3253 fix: fixed the mock collection in LHS search and restricted workspace [SPRW-1154]
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/workspace.repository.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/repositories/workspace.repository.ts
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/sub-component/history-table-expanded/HistoryTableExpanded.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-doc/RequestDoc.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#3255 feat: implement loader for environment and testflow creation [SPRW-751]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/tab.model.ts
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: bug

#3196 Fix the empty workspace page
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: bug

#3256 fix: curl import bug [SPRW-1146]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: pr-bugfix

#3258 fix: restricted to open orphan data from global search [SPRW-1155]
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-desktop/src/repositories/environment.repository.ts
  apps/@sparrow-desktop/src/repositories/testflow.repository.ts
  apps/@sparrow-desktop/src/repositories/workspace.repository.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/repositories/environment.repository.ts
  apps/@sparrow-web/src/repositories/testflow.repository.ts
  apps/@sparrow-web/src/repositories/workspace.repository.ts
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
Labels: pr-bugfix
