Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-07, with the labels that each got.

#3404 Build/linux prod workflow
  .github/workflows/sparrow-app-prod.yaml
Labels: bug, documentation, maintainer, enhancement

#3395 build: Add production release workflow
  .github/workflows/sparrow-app-prod.yaml
Labels: bug, documentation, maintainer, enhancement, first-time-contributor

#3392 chore(deps): upgrade tauri to v2.6.0
  .env.docker-setup
  README.md
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
  apps/@sparrow-desktop/src-tauri/gen/schemas/acl-manifests.json
  apps/@sparrow-desktop/src-tauri/gen/schemas/desktop-schema.json
  apps/@sparrow-desktop/src-tauri/gen/schemas/macOS-schema.json
  apps/@sparrow-desktop/src-tauri/src/main.rs
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  docker-compose.yml
  docs/ENVIRONMENT_VARIABLE_GUIDE.md
  docs/SELF_HOST.md
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
  scripts/sync-version.js
  yarn.lock
Labels: pr-bugfix, pr-doc, pr-build, pr-version-upgrade

#3422 fix: sidebar closing issue in web app SPRW-1435.
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
Labels: pr-bugfix

#3419 Fix: Testflow count issue on multiple clicks in the default workspace SPRW-1325.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte
Labels: pr-bugfix

#3447 Fix mock folder tag bug.
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: bug

#3449 fix: test flow multiple click issue on pop up SPRW-1325.
  packages/@sparrow-workspaces/src/features/workspace-default/components/card/Card.svelte
Labels: pr-bugfix

#3442 feat: animation support for AI panel and toggle buttons SPRW-1449.
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/ai-chat-animations.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/index.ts
Labels: feature

#3450 Revert "feat: animation support for AI panel and toggle buttons SPRW-1449."
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/ai-chat-animations.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/index.ts
Labels: maintainer

#3452 fix: LHS panel collection test flow not closing new user issue SPRW-1437.
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Labels: pr-bugfix

#3443 fix: logo compression issue in Teams panel (LHS) SPRW-1448.
  packages/@sparrow-teams/src/features/team-list/components/team-row/TeamRow.svelte
Labels: pr-bugfix

#3440 Feat: animation support for dropdown,options,shortcuts and button SPRW-1449.
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/ui/button/Button.svelte
  packages/@sparrow-library/src/ui/keyboardShortcuts/keyboardShortcuts.svelte
  packages/@sparrow-library/src/ui/options/Options.svelte
  packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
Labels: feature

#3457 fix: removed formatted notification []
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
Labels: pr-bugfix

#3420 feat: added disabled state to the import collection for ongoing validation request [SPRW-460]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/import-collection/components/file-upload/FileUpload.svelte
  packages/@sparrow-workspaces/src/features/import-collection/components/index.ts
  packages/@sparrow-workspaces/src/features/import-collection/components/text-upload/TextUpload.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
Labels: enhancement

#3458 fix: lag issue for empty folder SPRW-1428.
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
Labels: pr-bugfix

#3460 refactor: move curlconverter to svelte, remove api call
  apps/@sparrow-desktop/public/tree-sitter-bash.wasm
  apps/@sparrow-desktop/public/tree-sitter.wasm
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-desktop/vite.config.ts
  apps/@sparrow-web/public/tree-sitter-bash.wasm
  apps/@sparrow-web/public/tree-sitter.wasm
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/collection.service.ts
  apps/@sparrow-web/vite.config.ts
  package.json
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-workspaces/src/features/import-curl/layout/ImportCurl.svelte
  yarn.lock
Labels: pr-bugfix, pr-refactor

#3468 fix: app store build
  .github/workflows/sparrow-app-marketplace.yml
  apps/@sparrow-desktop/src-tauri/Cargo.lock
  apps/@sparrow-desktop/src-tauri/Cargo.toml
Labels: pr-build

#3472 fix: snap build
  .github/workflows/sparrow-app-marketplace.yml
  .github/workflows/sparrow-app-test-pipeline.yml
  .gitignore
  docs/pull_request_template.md
  snapcraft.yaml.in
Labels: bug, pr-build, documentation, maintainer, enhancement

#3481 feat: create signed msix build
  .github/workflows/sparrow-app-prod.yaml
  .github/workflows/sparrow-app-test-pipeline.yml
Labels: pr-build, documentation, maintainer, enhancement

#3484 Fix/msix build
  .github/workflows/sparrow-app-prod.yaml
  .github/workflows/sparrow-app-test-pipeline.yml
Labels: bug, documentation, maintainer, enhancement

#3486 Clone development
  .github/workflows/sparrow-app-marketplace.yml
  .github/workflows/sparrow-app-prod.yaml
  CHANGELOG.md
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/ai-chat-animations.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/index.ts
  snapcraft.yaml.in
Labels: documentation, maintainer, enhancement

#3487 Revert "Clone development"
  .github/workflows/sparrow-app-marketplace.yml
  .github/workflows/sparrow-app-prod.yaml
  CHANGELOG.md
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/ai-chat-animations.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/utils/index.ts
  snapcraft.yaml.in
Labels: maintainer

#3489 add msi and nsis in prod workflow
  .github/workflows/sparrow-app-prod.yaml
Labels: documentation, maintainer, enhancement

#3490 Development
  .github/workflows/sparrow-app-prod.yaml
Labels: bug, documentation, maintainer, enhancement

#3491 add gpg in linux job prod workflow
  .github/workflows/sparrow-app-prod.yaml
Labels: documentation, maintainer, enhancement

#3495 Release - 2.28.0
  .github/workflows/sparrow-app-prod.yaml
Labels: bug, documentation, maintainer, enhancement

#3505 fix: prevent vertical scrolling of tab bar issue for mac SPRW-1510.
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: pr-bugfix

#3506 fix: Rest Explorer saved export issue SPRW-1379.
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte
Labels: pr-bugfix

#3508 fix: tooltip slide animation positioning issue SPRW-1566.
  packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte
Labels: pr-bugfix

#3498 fix: missing auto-generated auth headers in test flow issue SPRW-169.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/RequestAuthTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#3513 fix: fixed the guest user login issue [SPRW-1615]
  apps/@sparrow-web/src/components/App.ts
Labels: pr-bugfix

#3514 patch: patch release for the trial flow
  apps/@sparrow-web/src/components/App.ts
Labels: released, pr-bugfix, pr-released

#3519 fix: added validation for email for invite workspace SPRW-1498.
  packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte
Labels: pr-bugfix

#3524 fix: added value length check in editort for window style space [SPRW-1622]
  packages/@sparrow-library/src/forms/editor/Editor.svelte
Labels: pr-bugfix

#3533 fix: Prompt Input tool tip issue in AI chatbot.
  packages/@sparrow-library/src/forms/select/Select.svelte
Labels: pr-bugfix

#3544 fix: fixed the placeholder size [SPRW-614]
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
Labels: pr-bugfix

#3543 fix: SPRW-1267-left-panel-workspace-name-has-space-but-its-being-truncated-to-early
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#3535 fix: AI request count issue in folder delete popup SPRW-1593.
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
Labels: pr-bugfix

#3536 fix: deselecting while deleting a environment issue SPRW-640.
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
Labels: pr-bugfix

#3539 fix: WebSocket connected input URL issue SPRW-755.
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: pr-bugfix

#3545 fix: Global search switching hub issue SPRW-883.
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
Labels: pr-bugfix

#3548 Fix tooltip bugs.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: bug

#3551 Fix: Input issue with Socket.IO during connection SPRW-1538.
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
Labels: pr-bugfix

#3512 fix: GraphQL response synchronization issue with the editor SPRW-192.
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
Labels: pr-bugfix
