Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-04, with the labels that each got.

#2885 Fix/stop propogation while altering teams settings change
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
  packages/@sparrow-teams/src/features/team-settings/components/settings-navigator/SettingsNavigator.svelte
  packages/@sparrow-teams/src/features/team-settings/layout/TeamSettings.svelte
Labels: bug

#2883 feat: updated team to hub for user [SPRW-557]
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/pages/auth-page/Auth.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/features/create-team/constants/description.ts
  packages/@sparrow-common/src/features/create-team/constants/name.ts
  packages/@sparrow-teams/src/features/leave-team/layout/LeaveTeam.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
  packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte
Labels: pr-feature

#2868 fix: top tab scroll
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
Labels: bug

#2899 fix: Fixed issue link check in the github workflow
  .github/workflows/pr-title-check.yaml
Labels: bug

#2897 feat: Key value pairs
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/utils/tabular-input-theme.ts
Labels: pr-refactor

#2901 Astitva/hub UI changes
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
Labels: pr-bugfix

#2900 fix : bugs solve in global Search and left panel workspace
  packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
Labels: bug

#2894 feat: add folder save button to web and desktop app
  apps/@sparrow-desktop/src/adapter/folder-tab.ts
  apps/@sparrow-desktop/src/adapter/index.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/tab.repository.ts
  apps/@sparrow-web/src/adapter/folder-tab.ts
  apps/@sparrow-web/src/adapter/index.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
  apps/@sparrow-web/src/repositories/tab.repository.ts
  packages/@sparrow-common/src/types/workspace/folder-tab.ts
  packages/@sparrow-common/src/utils/init-folder-tab.ts
  packages/@sparrow-common/src/utils/init-request-tab.ts
  packages/@sparrow-common/src/utils/init-workspace-tab.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
Labels: pr-feature

#2876 Fix: Graphql padding issue.
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
Labels: pr-bugfix

#2892 Feat: Websocket Implementation for Chatbot
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/layout/ChatBot.svelte
Labels: pr-feature

#2895 Feat: Clear Response Test flow.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#2905 Feat/implement workspace save feature for desktop and web
  apps/@sparrow-desktop/src/adapter/index.ts
  apps/@sparrow-desktop/src/adapter/workspace-tab.ts
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/workspace.repository.ts
  apps/@sparrow-web/src/adapter/index.ts
  apps/@sparrow-web/src/adapter/workspace-tab.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  packages/@sparrow-common/src/factory/init-tab.ts
  packages/@sparrow-common/src/types/workspace/workspace-tab.ts
  packages/@sparrow-common/src/utils/init-workspace-tab.ts
  packages/@sparrow-library/src/ui/avatar/Avatar.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/components/quick-help/QuickHelp.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/collection-count/CollectionCount.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
  packages/@sparrow-workspaces/src/hoc/WithOutlet.svelte
  packages/@sparrow-workspaces/src/hoc/index.ts
Labels: pr-feature

#2908 fix: typography bugs
  packages/@sparrow-common/src/components/SearchBar/SearchBar.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/sub-component/UserProfileModal.svelte
  packages/@sparrow-common/src/features/create-team/components/icon-uploader/IconUploader.svelte
  packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte
  packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
  packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
  packages/@sparrow-common/src/features/global-search/components/SearchBar/SearchBar.svelte
  packages/@sparrow-library/src/forms/label-field/LabelField.svelte
  packages/@sparrow-library/src/ui/modal/Modal.svelte
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-library/src/ui/toggle/Toggle.svelte
  packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/Profile.svelte
  packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Labels: pr-bugfix

#2904 fix: fixed the color for ai logo to avoid default color fallback in macOs
  packages/@sparrow-common/src/icons/SparrowAI.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
Labels: pr-bugfix

#2909 fix: fixed the env variables for websockets
  Sparrow-Web.Dockerfile
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  docker-compose.yml
Labels: pr-bugfix

#2912 feat: replaced hubUrl with api url in workspace, environment, team APIs [SPRW-558]
  .github/workflows/development.yaml
  .github/workflows/release.yaml
  .github/workflows/sparrow-web-dev.yml
  .github/workflows/sparrow-web-prod.yml
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/team.model.ts
  apps/@sparrow-desktop/src/models/workspace.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/environment.service.ts
  apps/@sparrow-desktop/src/services/team.service.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/team.model.ts
  apps/@sparrow-web/src/models/workspace.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/environment.service.ts
  apps/@sparrow-web/src/services/team.service.ts
  apps/@sparrow-web/src/services/workspace.service.ts
Labels: pr-feature

#2903 Feat: Testflow stop button.
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-common/src/types/workspace/testflow-tab.ts
  packages/@sparrow-library/src/icons/StopFilled.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#2902 build: fix docker compose sparrow auth env injection
  .env.docker-setup
  docker-compose.yml
Labels: pr-bugfix, pr-build

#2917 Feat/partial run testflow implementation
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/icons/ArrowExportRegular.svelte
  packages/@sparrow-library/src/icons/ArrowImportRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#2916 Feat: Drag and drop for New Test flow.
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-feature

#2919 fix: test-flow bottom panel bugs
  packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body/ResponseBody.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#2922 fix: test-flow bottom panel bugs
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
Labels: pr-bugfix

#2914 feat: sparrow chatbot and code blocks ui revamped
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  packages/@sparrow-common/src/icons/SparrowPrimaryIcon.svelte
  packages/@sparrow-library/src/icons/ArrowExpandRegular.svelte
  packages/@sparrow-library/src/icons/StopFilled.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/features/chat-bot/assests/ArrowExpand.svg
  packages/@sparrow-workspaces/src/features/chat-bot/assests/Copy.svg
  packages/@sparrow-workspaces/src/features/chat-bot/assests/index.ts
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-suggestion-box/AISuggestionBox.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/stores/chatbot-state.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: pr-feature

#2928 fix: fixed multiple reconnection attempts for websocket
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
Labels: pr-bugfix

#2923 fix: Test flow drag and drop body issue.
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-bugfix

#2932 feat: added huburl route for collection level apis []
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/collection.service.ts
Labels: pr-feature

#2927 fix: save response format correctly from top panel
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: pr-bugfix

#2930 fix: test flow scrollbar and auto-scroll to new key-value pairs
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
Labels: pr-bugfix

#2933 feat: added hub url route in testflow and fetch APIs [SPRW-558]
  apps/@sparrow-desktop/src/adapter/team.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/collection.service.ts
  apps/@sparrow-desktop/src/services/environment.service.ts
  apps/@sparrow-desktop/src/services/team.service.ts
  apps/@sparrow-desktop/src/services/testflow.service.ts
  apps/@sparrow-web/src/adapter/team.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/collection.service.ts
  apps/@sparrow-web/src/services/environment.service.ts
  apps/@sparrow-web/src/services/team.service.ts
  apps/@sparrow-web/src/services/testflow.service.ts
  packages/@sparrow-common/src/features/create-team/components/team-actions/TeamActions.svelte
  packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
  packages/@sparrow-common/src/features/create-team/constants/name.ts
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/TeamsProfile.svelte
  packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
Labels: pr-feature

#2921 fix:Expanding inputs bugs
  packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/utils/tabular-input-theme.ts
Labels: pr-bugfix

#2944 fix the delete response for web and desktop.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
Labels: pr-bugfix

#2939 fix: text-size in delete pop-up and icons size in workspace.
  packages/@sparrow-library/src/icons/SettingsRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
Labels: pr-bugfix

#2943 fix:sidebar-toggle
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
Labels: pr-bugfix

#2948 fix: validation message and url box edge
  packages/@sparrow-teams/src/features/create-workspace/components/workspace-team/WorkspaceTeam.svelte
  packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte
  packages/@sparrow-workspaces/src/utils/url-input-theme.ts
Labels: pr-bugfix

#2946 feat: added response streaming for AI chatbot
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-feature

#2949 fix: disable clear input CTA if editor is empty
  packages/@sparrow-workspaces/src/features/socket-explorer/components/request-body/SocketMessage.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/RequestMessage.svelte
Labels: pr-bugfix

#2954 fix: ui fixes for chatbot panel and model rename
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#2958 feat: added active sync in app [SPRW-561]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: pr-feature

#2961 fix: updated the folder sync logic in active sync[]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
Labels: pr-bugfix

#2962 feat: added active sync in web app [SPRW-561]
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/collection.service.ts
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
Labels: pr-feature

#2945 fix: Test flow arrow hover issue.
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
Labels: pr-bugfix

#2953 fix: resolve env UI breaking issue
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
Labels: pr-bugfix

#2964 fix: auto-scroll issue on macOS when adding key-value pair
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Labels: pr-bugfix

#2938 feat: added x-app-version header in Headers of all APIs []
  apps/@sparrow-desktop/src/containers/api/api.common.ts
  apps/@sparrow-web/src/containers/api/api.common.ts
Labels: pr-feature

#2942 solved ui issues
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
  packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
Labels: pr-bugfix

#2951 fix: save shortcuts on Collection, Workspace, Environment, WebSocket & Socket.IO
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
Labels: pr-bugfix

#2966 fix: remove onSaveWorkSapce check
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
Labels: pr-bugfix

#2974 feat:Invite flow non registered
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/repositories/team.repository.ts
  apps/@sparrow-web/src/services/team.service.ts
  packages/@sparrow-teams/src/features/invited-users/components/InviteRow.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-feature

#2970 fix: disable like dislike for empty messages
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: pr-bugfix

#2978 fix: fixed active sync UI issues []
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/services/collection.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/services/collection.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/stores/active-sync.ts
  packages/@sparrow-workspaces/src/stores/index.ts
Labels: pr-bugfix

#2967 fix: Test flow overflowing issue with long request time.
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
Labels: pr-bugfix

#2983 Invite flow bugs
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
  packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte
Labels: pr-bugfix

#2985 fix: restricted active sync for viewer and folder level count []
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
Labels: pr-bugfix

#2986 fix workspace dropdown.
  packages/@sparrow-common/src/components/header/Header.svelte
Labels: pr-bugfix

#2957 fix:text-size and toast in delete response pop-up.
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
Labels: pr-bugfix

#2993 fix: solved active sync bugs [SPRW-731]
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/collection.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-desktop/src/repositories/collection.repository.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/collection.model.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
  apps/@sparrow-web/src/repositories/collection.repository.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
Labels: pr-bugfix

#2992 Fix the background of active line in editor.
  packages/@sparrow-library/src/forms/editor/theme.ts
Labels: pr-bugfix

#2995 feat: added canny env for feedback []
  .github/workflows/development.yaml
  .github/workflows/release.yaml
  .github/workflows/sparrow-web-dev.yml
  .github/workflows/sparrow-web-prod.yml
  .vscode/settings.json
  Sparrow-Web.Dockerfile
Labels: pr-feature

#2994 Fix the url for report issue.
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
Labels: pr-bugfix

#2979 fix: red dot appearance and disappearance delay
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
Labels: pr-bugfix

#2996 fix: added dynamic expression to codemirror
  packages/@sparrow-library/src/forms/select/Select.svelte
  packages/@sparrow-library/src/icons/MathFormulaRegular.svelte
  packages/@sparrow-library/src/icons/index.ts
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/index.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/index.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: bug

#2997 fix the appearance of toast component.
  packages/@sparrow-library/src/ui/toast/Toast.svelte
  packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
Labels: pr-bugfix

#2998 fix: Error message size issue.
  packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
Labels: pr-bugfix

#2988 Fix: Testflow reponse button gap issue.
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
Labels: pr-bugfix

#3010 fix: added replace collection popup [SPRW-731]
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Labels: pr-bugfix

#3016 fix: fixed the last synced condition [SPRW-621]
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
Labels: pr-bugfix

#3020 build: Punit/pipeline update
  .github/sparrow-bot.json
  .github/workflows/pr-title-check.yaml
  .github/workflows/sparrow-bot.yml
Labels: bug, documentation

#3007 fix:redirection of report issue button. [SPRW-696]
  apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
Labels: pr-bugfix

#3006 fix the opening of collection, folder and request tab on click of expand button.
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
Labels: pr-bugfix

#3024 feat: add 2.22.1 patch release version
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: documentation

#3021 Feat: Testflow dynamic expression for Headers and parameters.
  packages/@sparrow-common/src/types/workspace/testflow-tab.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-library/src/forms/editor/theme.ts
  packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/index.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/functionOptionsData.ts
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/store/index.ts
  packages/@sparrow-workspaces/src/features/testflow-explorer/store/testflow.ts
Labels: pr-feature

#3008 fix the workspacelist header overlapping in mac.
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
Labels: pr-bugfix

#3033 feat: Dynamic expression headers fixes.
  packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
Labels: pr-bugfix

#3023 fix: removed "new request" in tab bar SPRW-767
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
Labels: pr-bugfix

#3039 feat: added public workspace flow
  .github/workflows/sparrow-app-development.yml
  .github/workflows/sparrow-app-prod.yaml
  .github/workflows/sparrow-webapp-dev.yml
  .github/workflows/sparrow-webapp-prod.yml
  Sparrow-Web.Dockerfile
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/constants/constants.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/workspace.model.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-desktop/src/repositories/workspace.repository.ts
  apps/@sparrow-desktop/src/services/workspace.service.ts
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/constants/constants.ts
  apps/@sparrow-web/src/database/database.ts
  apps/@sparrow-web/src/models/workspace.model.ts
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
  apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/src/repositories/team.repository.ts
  apps/@sparrow-web/src/repositories/workspace.repository.ts
  apps/@sparrow-web/src/services/collection.service.ts
  apps/@sparrow-web/src/services/environment.service.ts
  apps/@sparrow-web/src/services/testflow.service.ts
  apps/@sparrow-web/src/services/workspace.service.ts
  packages/@sparrow-common/src/dto/workspace-dto.ts
  packages/@sparrow-common/src/enums/workspace.enum.ts
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-feature

#3044 feat: added workspace public modal [SPRW-853]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  apps/@sparrow-web/src/components/App.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
  packages/@sparrow-common/src/features/index.ts
  packages/@sparrow-common/src/features/public-workspace/index.ts
  packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
  packages/@sparrow-common/src/features/public-workspace/layout/index.ts
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
Labels: pr-feature

#3046 Update the UI of workspace.
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
  packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte
Labels: pr-style, enhancement

#3045 feat: Dynamic expression model.
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
  packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: pr-refactor

#3036 change in ui of workspace.
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: feature

#3034 feat: AI debugging and error handling with merge/diff view
  package.json
  packages/@sparrow-common/src/types/workspace/http-request-tab.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/assests/ArrowTrendingSparkle.svg
  packages/@sparrow-workspaces/src/features/chat-bot/assests/index.ts
  packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/layout/ChatBot.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/RequestBody.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/form-data/FormData.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/raw/Raw.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-headers/RequestHeaders.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/request-parameters/RequestParameters.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
  yarn.lock
Labels: pr-feature

#3051 fix: fixed UI changes in workspace []
  packages/@sparrow-library/src/ui/tags/Tags.svelte
  packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
Labels: pr-bugfix
