Repository sparrowapp-dev/sparrow-app, pull requests merged in 2025-01, with the labels that each got.

#2390 feat: Implement HTTP request form data handling in web app
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  apps/@sparrow-web/src/containers/api/api.common.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
  packages/@sparrow-common/src/utils/base64Converter.ts
  packages/@sparrow-common/src/utils/index.ts
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Labels: story

#2383 fix: updated UI image of sparrow edge in Teams
  packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
Labels: bug

#2393 Feat/testflow regression issues
  apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/adapter/request-tab.ts
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug

#2395 fix: fixed create account btn z-index [#2381]
  apps/@sparrow-web/src/components/App.ts
  packages/@sparrow-common/src/components/banner/login-banner.svelte
  packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
Labels: bug

#2396 fix: reupload form data files
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Labels: bug

#2398 fix: guest user regression issue
  apps/@sparrow-web/index.html
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/components/header/sub-component/PopupHint.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
Labels: bug

#2406 feat: upgrade app version
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src-tauri/tauri.conf.json
  apps/@sparrow-web/package.json
  package.json
  packages/@sparrow-common/package.json
  packages/@sparrow-library/package.json
  packages/@sparrow-support/package.json
  packages/@sparrow-teams/package.json
  packages/@sparrow-types/package.json
  packages/@sparrow-workspaces/package.json
Labels: documentation

#2424 feat: config storybook to the sparrow app
  package.json
  packages/@sparrow-storybook/.gitignore
  packages/@sparrow-storybook/.storybook/main.js
  packages/@sparrow-storybook/.storybook/preview.js
  packages/@sparrow-storybook/README.md
  packages/@sparrow-storybook/jsconfig.json
  packages/@sparrow-storybook/package.json
  packages/@sparrow-storybook/src/stories/Button.stories.js
  packages/@sparrow-storybook/src/stories/assets/accessibility.png
  packages/@sparrow-storybook/src/stories/assets/accessibility.svg
  packages/@sparrow-storybook/src/stories/assets/addon-library.png
  packages/@sparrow-storybook/src/stories/assets/assets.png
  packages/@sparrow-storybook/src/stories/assets/avif-test-image.avif
  packages/@sparrow-storybook/src/stories/assets/context.png
  packages/@sparrow-storybook/src/stories/assets/discord.svg
  packages/@sparrow-storybook/src/stories/assets/docs.png
  packages/@sparrow-storybook/src/stories/assets/figma-plugin.png
  packages/@sparrow-storybook/src/stories/assets/github.svg
  packages/@sparrow-storybook/src/stories/assets/share.png
  packages/@sparrow-storybook/src/stories/assets/styling.png
  packages/@sparrow-storybook/src/stories/assets/testing.png
  packages/@sparrow-storybook/src/stories/assets/theming.png
  packages/@sparrow-storybook/src/stories/assets/tutorials.svg
  packages/@sparrow-storybook/src/stories/assets/youtube.svg
  packages/@sparrow-storybook/src/stories/introduction.mdx
  packages/@sparrow-storybook/svelte.config.js
  packages/@sparrow-storybook/vite.config.js
  packages/@sparrow-storybook/yarn.lock
  yarn.lock
Labels: story

#2426 feat: add storybook build server
  package.json
  packages/@sparrow-storybook/package.json
  packages/@sparrow-storybook/src/stories/Button.stories.js
Labels: design, devops

#2434 fix: added mutation tab in graphql and fixed known bugs [#2419]
  apps/@sparrow-desktop/package.json
  apps/@sparrow-desktop/src/adapter/graphql-tab.ts
  apps/@sparrow-desktop/src/database/database.ts
  apps/@sparrow-desktop/src/models/tab.model.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
  apps/@sparrow-desktop/src/services/collection.service.ts
  package.json
  packages/@sparrow-common/src/components/default-header/DefaultHeader.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/types/workspace/graphql-request-dto.ts
  packages/@sparrow-common/src/types/workspace/graphql-request-tab.ts
  packages/@sparrow-common/src/utils/init-graphql-tab.ts
  packages/@sparrow-library/src/forms/editor/Editor.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
  yarn.lock
Labels: bug, known issue

#2444 fix: added flow to not overwrite valid query [#2420]
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
  apps/@sparrow-web/index.html
  packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
Labels: known issue

#2450 feat: added logos and layout storybook docuentation [#2411]
  apps/@sparrow-storybook/.storybook/main.js
  apps/@sparrow-storybook/src/stories/Layout/Layout.docs.mdx
  apps/@sparrow-storybook/src/stories/Logos/Logos.docs.mdx
  apps/@sparrow-storybook/src/stories/assets/Mask-group.png
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow1.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow10.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow11.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow12.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow13.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow14.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow15.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow2.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow3.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow4.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow5.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow6.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow7.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow8.svg
  apps/@sparrow-storybook/src/stories/assets/logos-sparrow9.svg
Labels: story

#2451 feat: added colour palette and iconography documentation in storybook…
  apps/@sparrow-storybook/src/stories/Color/Color.docs.mdx
  apps/@sparrow-storybook/src/stories/Iconography/Iconography.docs.mdx
  apps/@sparrow-storybook/src/stories/assets/color-sparrow1.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow1.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow2.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow3.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow4.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow5.svg
  apps/@sparrow-storybook/src/stories/assets/icon-sparrow6.svg
Labels: documentation, story

#2452 Storybook - Shadows #2413
  apps/@sparrow-storybook/src/stories/Shadow/Shadow.docs.mdx
Labels: task

#2456 Storybook - Spacing #2412
  apps/@sparrow-storybook/src/stories/Spacing/Spacing.docs.mdx
Labels: task

#2458 fix: ui & content fix in storybook []
  apps/@sparrow-storybook/src/stories/Color/Color.docs.mdx
  apps/@sparrow-storybook/src/stories/Iconography/Iconography.docs.mdx
  apps/@sparrow-storybook/src/stories/Layout/Layout.docs.mdx
  apps/@sparrow-storybook/src/stories/Logos/Logos.docs.mdx
Labels: documentation

#2446 UI issue in webapp #2345
  packages/@sparrow-library/src/forms/Input/Input.svelte
Labels: bug

#2430 feat: Run button icon and text is not properly aligned in webapp #2418
  packages/@sparrow-workspaces/src/components/drop-button/DropButton.svelte
Labels: bug

#2461 fix: updated the import path for the typography []
  apps/@sparrow-storybook/src/stories/Typography/Typography.docs.mdx
Labels: bug

#2465 Storybook - Spacing #2412
  apps/@sparrow-storybook/src/stories/Spacing/Spacing.docs.mdx
Labels: task

#2482 fix : API Request Count
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
  packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
Labels: story

#2489 Feat/add type
  apps/@sparrow-desktop/.env.example
  apps/@sparrow-desktop/src/pages/help-page/HelpPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  apps/@sparrow-web/.env.example
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
  apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
  packages/@sparrow-common/src/components/header/Header.svelte
  packages/@sparrow-common/src/features/download-app/DownloadApp.svelte
  packages/@sparrow-common/src/types/teams/team-base.ts
  packages/@sparrow-common/src/types/teams/team-dto.ts
  packages/@sparrow-common/src/types/teams/team-method.ts
  packages/@sparrow-common/src/types/workspace/collection-base.ts
  packages/@sparrow-common/src/types/workspace/http-request-base.ts
  packages/@sparrow-common/src/types/workspace/workspace-base.ts
  packages/@sparrow-common/src/types/workspace/workspace-dto.ts
  packages/@sparrow-common/src/utils/conversion.helper.ts
  packages/@sparrow-support/package.json
  packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
  packages/@sparrow-teams/src/features/recent-apis/layout/RecentApi.svelte
  packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
  packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
  packages/@sparrow-workspaces/.eslintrc.json
  packages/@sparrow-workspaces/src/constants/collectionGifs.constants.ts
  packages/@sparrow-workspaces/src/constants/environmentGifs.constants.ts
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Labels: enhancement

#2495 feat: revamped tooltip and added extra properties [#2466]
  apps/@sparrow-desktop/src/main.ts
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  apps/@sparrow-storybook/src/stories/Tooltip/Tooltip.docs.mdx
  apps/@sparrow-web/src/main.ts
  apps/@sparrow-web/src/pages/Teams/Teams.svelte
  packages/@sparrow-common/src/components/header/sub-component/PopupHint.svelte
  packages/@sparrow-common/src/components/header/sub-component/UserProfileModal.svelte
  packages/@sparrow-common/src/components/sidebar/SidebarItem.svelte
  packages/@sparrow-library/package.json
  packages/@sparrow-library/src/styles/style.scss
  packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte
  packages/@sparrow-support/src/features/add-feedback/layout/AddFeedback.svelte
  packages/@sparrow-support/src/features/discord-card/layout/DiscordCard.svelte
  packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
  packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
  packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
  packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
  packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
  packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
  packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
  packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
  packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
  packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
  packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
  packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
  packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-status/ResponseStatus.svelte
  packages/@sparrow-workspaces/src/features/testflow-explorer/components/save-testflow/SaveTestflow.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
  packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: story, design

#2494 DS - Side navigation rails #2462
  apps/@sparrow-desktop/src/components/app.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
  apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
  apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
  apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
  apps/@sparrow-storybook/.storybook/preview.js
  apps/@sparrow-storybook/src/stories/Navigation.stories.js
  apps/@sparrow-storybook/src/stories/Navigation/Navigation.docs.mdx
  apps/@sparrow-storybook/src/stories/assets/collections-hovered.svg
  apps/@sparrow-storybook/src/stories/assets/collections-selected.svg
  apps/@sparrow-storybook/src/stories/assets/collections.svg
  apps/@sparrow-storybook/src/stories/assets/help-hovered.svg
  apps/@sparrow-storybook/src/stories/assets/help-selected.svg
  apps/@sparrow-storybook/src/stories/assets/help.svg
  apps/@sparrow-storybook/src/stories/assets/home-hovered.svg
  apps/@sparrow-storybook/src/stories/assets/home-icon.svg
  apps/@sparrow-storybook/src/stories/assets/home-selected.svg
  apps/@sparrow-storybook/src/stories/assets/index.ts
  apps/@sparrow-storybook/src/stories/assets/settings-hovered.svg
  apps/@sparrow-storybook/src/stories/assets/settings-selected.svg
  apps/@sparrow-storybook/src/stories/assets/settings.svg
  apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
  packages/@sparrow-common/package.json
  packages/@sparrow-common/src/components/index.ts
  packages/@sparrow-common/src/components/sidebar/Sidebar.svelte
  packages/@sparrow-common/src/components/sidebar/SidebarItem.svelte
  packages/@sparrow-common/src/components/sidebar/common/help-hovered.svg
  packages/@sparrow-common/src/components/sidebar/common/help-selected.svg
  packages/@sparrow-common/src/components/sidebar/common/help.svg
  packages/@sparrow-common/src/components/sidebar/common/home-hovered.svg
  packages/@sparrow-common/src/components/sidebar/common/home-icon.svg
  packages/@sparrow-common/src/components/sidebar/common/home-selected.svg
  packages/@sparrow-common/src/features/index.ts
  packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
  packages/@sparrow-common/src/features/sidebar/images/collections-hovered.svg
  packages/@sparrow-common/src/features/sidebar/images/collections-selected.svg
  packages/@sparrow-common/src/features/sidebar/images/collections.svg
  packages/@sparrow-common/src/features/sidebar/images/help-hovered.svg
  packages/@sparrow-common/src/features/sidebar/images/help-selected.svg
  packages/@sparrow-common/src/features/sidebar/images/help.svg
  packages/@sparrow-common/src/features/sidebar/images/home-hovered.svg
  packages/@sparrow-common/src/features/sidebar/images/home-icon.svg
  packages/@sparrow-common/src/features/sidebar/images/home-selected.svg
  packages/@sparrow-common/src/features/sidebar/images/index.ts
  packages/@sparrow-common/src/features/sidebar/images/settings-hovered.svg
  packages/@sparrow-common/src/features/sidebar/images/settings-selected.svg
  packages/@sparrow-common/src/features/sidebar/images/settings.svg
  packages/@sparrow-common/src/features/sidebar/index.ts
  packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
  packages/@sparrow-common/src/types/sidebar/sidebar-base.ts
  packages/@sparrow-library/src/ui/index.ts
Labels: story

#2525 DS - Side navigation rails #2462
  packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
  packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
Labels: story

#2550 feat: shorten the app version []
  apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
  packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
Labels: bug
